### ISSUE TITLE
Bug: Kiln incorrectly throws errors about component lists 

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#1002]
## Bug
Kiln incorrectly throws an error when loading a fresh, local install of nymag.com/strategist

```
Uncaught (in promise) Error: two-column-layout → top contains child elements that are not components! All child elements of component lists must be components.
    at clay-kiln-edit.js:30421
    at clay-kiln-edit.js:48075
    at forEach (clay-kiln-edit.js:26728)
    at assertDirectParent (clay-kiln-edit.js:30419)
    at handler (clay-kiln-edit.js:30453)
    at arrayEach (clay-kiln-edit.js:26752)
    at forEach (clay-kiln-edit.js:26728)
    at addFieldDecorators (clay-kiln-edit.js:34037)
    at decorate (clay-kiln-edit.js:34061)
    at Object.decorateAll (clay-kiln-edit.js:34075)
```

the `top` component list only has ads and the global-nav components. `top`, ad and the global nav components all have `data-uris`, so they should be read as components.

**Comment by nelsonpecora** [comment]
This is on the index page, yeah? I'll take a look.

**Comment by nelsonpecora** [comment]
I can't repro this locally on any index page.

**Comment by amycheng** [comment]
I'm getting it on all pages on the Strategist. I'm using the first runs and
npm linked kiln latest

**Comment by nelsonpecora** [comment]
Try clearing your local and re-bootstrapping, since I'm doing the exact same thing and not seeing any error

**Comment by nelsonpecora** [comment]
By the by, I updated the error messaging in commit 4828cda, so it should be clearer when people hit it

**Comment by nelsonpecora** [comment]
Ah! You were right, I'm seeing it now. Investigating...

**Comment by nelsonpecora** [comment]
... I'm a dumb dumb. Fixing now!
