### ISSUE TITLE
Users are not added to list of collaborators 

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1003]
Something is fishy about this article: 
• Users are not added to list of collaborators (copy editor reported that this has happened on several articles)
• The publish date is "47 years ago"

http://www.thecut.com/2017/11/an-oral-history-of-feminist-group-new-york-radical-women.html?edit=true

**Comment by pfeytser** [comment]
I thought so too, but I just got a few more examples from copy: 

http://nymag.com/daily/intelligencer/2017/11/are-both-sides-in-gop-civil-war-taking-aim-at-roy-moore.html?edit=true

http://www.thecut.com/2017/11/how-politics-affects-thanksgiving-dinners.html?edit=true

**Comment by nelsonpecora** [comment]
Hmmm! Who worked on these? I can check the trackjs error logs and see if they show anything.

**Comment by pfeytser** [comment]
Eliza McCarthy worked on these

**Comment by pfeytser** [comment]
More links: 
http://www.thecut.com/2017/11/carter-page-wears-red-hat-around-capitol-hill.html?edit=true#

**Comment by nelsonpecora** [comment]
Hmm, I don't see eliza mccarthy in trackjs at all

**Comment by nelsonpecora** [comment]
Ok, I looked through these articles and it seems like NONE of them were ever added to elastic, which would account for the weird publish date and the lack of contributors. @jonwinton any ideas?

**Comment by nelsonpecora** [comment]
Hey @jonwinton was this resolved?
