### ISSUE TITLE
Validate component data properties are camelcased

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1004]
## Idea
On page load, validate that all component data properties are camelcased, and show a warning or error otherwise.

**Comment by byronhulcher** [comment]
@nelsonpecora has more background info on this

**Comment by byronhulcher** [comment]
(imo you should be able to use whatever format you want for component property names but thats just meeeeeeeeeeee)

**Comment by nelsonpecora** [comment]
Actually,

**Comment by nelsonpecora** [comment]
as of commit b3ff4fe this (in docs) requirement is now enforced in code
