### ISSUE TITLE
Unintended author names and tags are saved and appear in the drop down.

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1007]
* Use list service.
* This only works for lists and not Elastic.
* Use allowRemove argument.
* Also add allowCreate argument to automatically add things to list in Kiln.
* Trim things that are automatically added.

Note: autocomplete might be getting a little more powerful (Update auto-complete behavior to query Elastic), so this deletion functionality should probably work with both lists and elastic indices. (What security / data-loss concerns do we have when deleting items from an elastic index?)

![delete](https://user-images.githubusercontent.com/447522/32862449-2496f0de-ca26-11e7-9482-c537f03828da.png)

**Comment by nelsonpecora** [comment]
Per our discussion, I think we should combine the schema args into a single `modifyList` argument, which would:

1. add an `X` button on items, to remove them from the list
2. automatically add _new_ items to the list (via the store)

**Comment by pfeytser** [comment]
###Acceptance Criteria

* When the autocomplete list appears, I can click the 'x' on a specific item, which will delete it. 
* The next time I type the same word, the item I deleted does not appear in autocomplete.

**Comment by pfeytser** [comment]
Acceptance Criteria

- [ ] When autocomplete options appear, there is an X next to each item. 
- [ ] When I click the X, it deletes that option from the list so it does not appear in autocomplete anymore. 
- [ ] This works for authors and tags.

**Comment by nelsonpecora** [comment]
@pfeytser note that this should only enable that UI affordance in fields where the option is enabled (article authors and article tags).

Also implementation note: there are other components using `simple-list` that would have to be updated if they wanted to enable this functionality (feature ledes, etc), and if kiln also _adds_ new items to the list then those components' `model.save()` methods would have to be updated to not save the items to the list a second time.
