### ISSUE TITLE
Bug: wysiwyg popup appears under description

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1008]
## Bug

When editing wysiwyg text the Quill toolbar is layered under the description field, making it difficult (or in some cases impossible) to use the toolbar buttons.

## Proposed Solution

Bump up the z (bump it up)

**Comment by pfeytser** [comment]
QA Acceptance Criteria

- In the article circulation section, when I highlight a word in the Twitter headline, the formatting toolbar clearly appears over the description text below and is clickable.

**Comment by medihaaziz** [comment]
@pfeytser Passes QA

**Comment by medihaaziz** [comment]
@pfeytser and @nelsonpecora the strike through format is not working here either

**Comment by nelsonpecora** [comment]
It's working for me locally (and that's out of scope for this ticket)
