### ISSUE TITLE
Entity Picker

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1010]
A specialized kiln input that allows searching and fetching of entities, which will populate specified fields in a form.

**Comment by pfeytser** [comment]
@jonwinton Was this a feature request you put in?

**Comment by pfeytser** [comment]
Types are deprecated from Amphora Search so the API does not need to include that.

**Comment by nelsonpecora** [comment]
Use case: article picker

**Comment by nelsonpecora** [comment]
Many use cases in [the ticket for collections, aka shared component data](https://github.com/clay/clay-kiln/issues/1171)

![screen shot 2018-04-19 at 10 29 38 am](https://user-images.githubusercontent.com/447522/39005138-537d88f6-43cd-11e8-88aa-d559406c7a71.png)

**Comment by nelsonpecora** [comment]
Article picker has been built as a custom plugin.
