### ISSUE TITLE
Don't resize a form down when remove item from complex list

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1013]

**Comment by nelsonpecora** [comment]
already done!

**Comment by pfeytser** [comment]
QA Acceptance Criteria

- In the source link component, after I remove an item, the overlay window doesn't resize down.

**Comment by medihaaziz** [comment]
@pfeytser Passes QA Test link: 
http://kiln-510.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cjaa2wgs4000n0lpapc1mnbey.html?edit=true#source-links~cjaa4fmq7000m3a5rmg388ti4~content
