### ISSUE TITLE
Publish message time is a little off

### ISSUE THREAD

**Issue by davidandrewfrey** [clay/clay-kiln#1018]
## Bug
Opened up a prd Vulture article that had been recently published and noticed that the Publish message stated:
`Published almost 48 years ago`

Screenshot:
![screen-shot-2017-11-20-at-5 04 02-pm](https://user-images.githubusercontent.com/4967321/33044253-3929e3e6-ce16-11e7-8c28-07399c13a591.jpg)

**Comment by nelsonpecora** [comment]
duplicate of #1003
