### ISSUE TITLE
Text Formatting Bubble Appears Out of View

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1020]
To reproduce: 
Highlight the first word in the Twitter description

<img width="714" alt="screen shot 2017-11-21 at 3 35 01 pm" src="https://user-images.githubusercontent.com/10674066/33095453-c0790366-ced1-11e7-88e1-abe82ad28029.png">

**Comment by nelsonpecora** [comment]
Hmm, what did this first start happening? If I set everything above that to `overflow: visible` it's still being hidden.

**Comment by pfeytser** [comment]
Ever since we made them bigger on `5.1` I think

**Comment by nelsonpecora** [comment]
I think there's a Quill config that might alleviate this issue. Testing locally...
