### ISSUE TITLE
Headlines & Teasers: Character Count Miscalculation on Formatted Text

### ISSUE THREAD

**Issue by dmabuada** [clay/clay-kiln#1021]
## Bug
Formatted text adds additional characters (this extends to more than just the Twitter hed). From the #help channel:

> weirdly, the character counter in the twitter hed field of this post seems to be broken -- it keeps saying this hed is 76 characters but i checked in word and it's only 58 (4 Iconic The Room Scenes, Recreated in The Disaster Artist) 
http://www.vulture.com/pages/cjaiiufcj00ylxcy66pxooo3i.html?edit=true#

**Comment by nelsonpecora** [comment]
I can confirm, the length is off when using formatting. Specifically, it's not stripping the tags before checking the length

**Comment by nelsonpecora** [comment]
Note: It's specifically an issue with the `wysiwyg` length display, _not_ the field validation (which is stripping tags) _or_ the pre-publish validation (ditto)
