### ISSUE TITLE
Archiving Pages

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1033]
Depends on [`amphora-search` work](https://trello.com/c/Ot3SkB9M/46-archive-pages)

* [x] Pages in `pages` index will have an `archived` property (boolean)
* [x] Clay Menu should have an `archived` option in the status selectors (on mobile and desktop)
* [x] All `pages` queries should (by default) _not_ include archived pages (only queries with `archived` selected should include them)
* [x] Page archiving / un-archiving is a section of the publish drawer (below custom url)
* [x] Published / Scheduled pages cannot be archived (button should be disabled, with a note explaining)
* [x] Archived pages cannot be published or scheduled (buttons should be disabled, with a note explaining)
* [x] Archived pages can be un-archived (button will be disabled, but the status section at the top of the publish drawer should have an "unarchive" button)

**Comment by jonwinton** [comment]
Reminder to add amphora-search peer dependency to Kiln

**Comment by nelsonpecora** [comment]
![screen shot 2017-12-06 at 3 04 48 pm](https://user-images.githubusercontent.com/447522/33682840-d29103fc-da96-11e7-8897-96cf066bff6f.png)
