### ISSUE TITLE
Kiln mobile scrolling issues

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1037]
On mobile, scrolling is very difficult because the `component-list` dragdrop functionality is triggered. We should improve this so the mobile experience is good.

**Comment by nelsonpecora** [comment]
We should discuss this before updating the dragdrop code

**Comment by pfeytser** [comment]
Investigate if sortable.js can do tap and hold drag-drop.

**Comment by nelsonpecora** [comment]
It doesn't really do that automatically, unfortunately

**Comment by nelsonpecora** [comment]
There are a few [workarounds](https://github.com/bevacqua/dragula/issues/289) and [open pull requests](https://github.com/bevacqua/dragula/pull/517) to add a grab delay to dragula, but it doesn't look like it's being actively maintained. We should probably switch libraries rather than trying to hack it in ourselves.

**Comment by nelsonpecora** [comment]
Investigation is complete. We should switch to sortable.js, and use a 100ms delay (rather than a pixel deadzone) to solve both the clicking-into-things issue and the mobile scrolling issue.
