### ISSUE TITLE
"Unpublished Changes" status does not work consistently

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1043]
"Unpublished Changes" only appeared the first time that I made a change on a published article. On every subsequent article that I tried this, the status did not change.

**Comment by nelsonpecora** [comment]
When I publish a page for the first time, it sets the `publishTime` in the `pages` index. When I publish it again, it sets `publishTime` to `null`. This is an issue in `amphora-search`.

**Comment by nelsonpecora** [comment]
Issue moved to [clay/amphora-search #39](https://github.com/clay/amphora-search/issues/39) via [**ZenHub**](https://www.zenhub.com/)
