### ISSUE TITLE
Validating on _componentList fields

### ISSUE THREAD

**Issue by zonika** [clay/clay-kiln#1047]
I need to be able to add validation to component list fields in kiln. For example, if I have a componentList that is required and needs to be between 5 and 300 items long, it would be nice to just specify that in the schema the way we do with input fields, rather than writing a custom plugin for kiln (which I am doing now).

**Comment by nelsonpecora** [comment]
I don't want to add another validator until we standardize the `helper` methods, since otherwise we're just re-implementing a bunch of code (that honestly needs more testing as-is)
