### ISSUE TITLE
User feedback: Component select on hover problem

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1048]
Comment from Skye: 

There’s been an issue with a component’s view changing on hover (which we’re fixing) which led to a general discussion of kiln’s new “select on hover” functionality. Seems like everyone is finding it very hard to use. Particularly when you have to use “find on page” to get to a parent component, and then try to get the mouse to the toolbar before the hover shifts the selection away. There was a bit of frustration in the group, so wanted to pass along a heads up.

**Comment by nelsonpecora** [comment]
Maybe this is a good argument for figuring out keyboard shortcuts for settings / add / etc?

What's the use case where users hit this issue? i.e. are they trying to get into the parent settings, or looking at info, or adding/adding another/duplicating/removing the parent?

**Comment by nelsonpecora** [comment]
@pfeytser what are your thoughts? I'm kind of at an impasse.

**Comment by pfeytser** [comment]
The main issue that some parent components are not easily clickable, like imagine if the greatest hits component didn't have a title. That hover area for the parent is super tiny and not easily triggerable. Before Kiln 5, users would just use Find on Page to select the component, then mouse over there to click on settings on the component selector. But now, because hover triggers other component selectors, it's impossible to get there in time. 

My solution:
Make clicking the product name in Find on Page the same as clicking the component title on page validation erorrs. Also, add the settings gear next to the component name on Find on Page, just like under the head tab. 

What do you think?

**Comment by nelsonpecora** [comment]
Hmm. I understand the latter one (adding a settings icon to the list), but I'm not sure what you mean with "clicking the component title on page validation erorrs"

**Comment by pfeytser** [comment]
Under the health tab, if there are errors, you can click field names to open them.

**Comment by pfeytser** [comment]
Though, the validation errors there are related to specific fields, not components. Can we open the first field in the component when a user clicks it on Find on Page?

**Comment by pfeytser** [comment]
1. When building components, editable elements should have placeholders. 
2. In Find on Page, add the settings gear icon next to the components that have settings.
