### ISSUE TITLE
Add public link to "published" snackbar

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1049]
A conversation earlier today: 

<img width="740" alt="screen shot 2017-12-06 at 10 51 10 am" src="https://user-images.githubusercontent.com/10674066/33682226-cf320302-da94-11e7-8eee-b047306ca9d5.png">

**Comment by nelsonpecora** [comment]
Hmm. Is this an actual problem, or a first user / education thing?

**Comment by pfeytser** [comment]
@nelsonpecora Perhaps. It is very subtle. After I publish an article, I keep moving my mouse to the snackbar notification thinking the button in it will take me to the published page.

**Comment by nelsonpecora** [comment]
I was thinking about that when I wrote the `Published` snackbar, but all of the other ones are either "retry" or "undo", hence the button that's currently there. I suppose we could make the link larger, but I don't think that would actually make it easier to find (if you don't know where it is, having a larger link won't help, and if you do know where it is, it's pretty easy to find with the alternate color it uses)

**Comment by pfeytser** [comment]
When a user publishes an article, the vast majority of them then want to see the article. That notification could be more useful if it said "View Article" instead, which would take you to the public version of the page. Unpublishing an article is very easy to find. 

I really like what Google does when you dismiss an event reminder: 

<img width="1552" alt="screen shot 2017-12-07 at 11 21 29 am" src="https://user-images.githubusercontent.com/10674066/33736921-73203664-db62-11e7-8498-fd6e92e01b4c.png">

**Comment by nelsonpecora** [comment]
Fair enough. Let's change it.

**Comment by nelsonpecora** [comment]
added in commit 2b42caa
