### ISSUE TITLE
Bug: Tabbed complex list does not set height correctly

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1052]
## Bug
When editing a complex list in a tabbed overlay, the overlay background is collapsed to the height of the header. The contents are still visible on a transparent background. This only happens when the complex list does not appear in the first tab of the overlay.

When the complex list is in the first tab of the overlay the background does not collapse, but when the add/remove buttons cause an item to expand the list overflows outside the overlay background.

## Reproduction steps
1) Add a new component which has a complex list in a tabbed overlay (complex dropdown in `sites`)
2) Select the complex list tab, the "add items" button is shown
3) Select "add items". The item is added, the overlay background briefly expands to contain it before collapsing down to the header height
4) Close the overlay. Reopen it, select the tab with the complex list. The overlay is the correct height
5) Select "add another". The item is added, the overlay collapses again.

**Comment by nelsonpecora** [comment]
Thanks! I'll take a look

**Comment by nelsonpecora** [comment]
Do you have an example of a component with a complex-list in a tabbed form (in a tab other than the first one)?

**Comment by pfeytser** [comment]
@fraddski Do you know which component this was happening in?

**Comment by fraddski** [comment]
@pfeytser complex dropdown

**Comment by fraddski** [comment]
I'm also seeing this behavior with fields hidden using `reveal` - when they become visible in a non-selected tab the tab pane does not adjust its height to contain them.

I'm on kiln 5.8.3

**Comment by nelsonpecora** [comment]
@fraddski do you have an example of a component with a `_reveal`'d field that would be triggered in a background tab? I have a possible fix, but no way to test it.

**Comment by fraddski** [comment]
@nelsonpecora the `congress-prediction` component in sites does this.
