### ISSUE TITLE
On templates, tabs in Find on Page are not clickable

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1053]

**Comment by nelsonpecora** [comment]
I can't replicate this. I went to a new page template, opened "Find on Page", then clicked through the tabs. You have to close the "you're on a page template" alert to be able to click them, because (on most non-super-wide screens) the drawer is behind the alert.

**Comment by pfeytser** [comment]
The viewport here is narrower than my laptop screen. Looks like the margins around the alert are creating a click dead zone. I typically don't close the alert to remind myself I'm on a template. 

<img width="1493" alt="screen shot 2017-12-07 at 3 16 00 pm" src="https://user-images.githubusercontent.com/10674066/33736804-f317e430-db61-11e7-9fdb-442c127c1d45.png">

**Comment by pfeytser** [comment]
If you leave the notification alone and scroll, the dead zone applies to all content that scrolls in the background.

**Comment by nelsonpecora** [comment]
Ahhh, roger. I know how to fix this! (note to self: it's the same issue as the area around the snackbar)
