### ISSUE TITLE
Component property 'style' clashes with component settings

### ISSUE THREAD

**Issue by reubenson** [clay/clay-kiln#1054]
## Bug
A bug was reported in #help where `newsletter-flex-text` settings were not editable - click settings renders the gray overlay, but does not render the modal, and does not generate errors in console. In locally debugging this issue, it was determined that a property on the component named 'style' was the culprit for breaking the settings edit modal.

**Comment by nelsonpecora** [comment]
I don't see anything in kiln that would trigger this.
