### ISSUE TITLE
Bug: WYSIWYG phrase button is too small

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1055]
The "phrase" button in the WYSIWYG toolbar uses text, while the others use SVGs. When the buttons were made larger the SVGs were adjusted to scale up, but the text appears at the old, smaller size.

![image](https://user-images.githubusercontent.com/6829410/33742273-926adc32-db75-11e7-914d-0ee6c3e2879b.png)

**Comment by nelsonpecora** [comment]
Good catch!
