### ISSUE TITLE
Archive Even If Validation Fails

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1063]
Right now a page has to be publishable to be archivable. It would be nice to be able to archive it no matter what.

**Comment by nelsonpecora** [comment]
Actually, I think we need a bigger discussion, because you cannot "unpublish" or "unschedule" if the health check fails.

**Comment by pfeytser** [comment]
* Don't disable publish tab when health fails.
* Set active tab to Health when opening form when validation fails.
* Disable publish form and include message with link to Health tab when validation fails. 
* All other actions in Publish tab are allowed.
