### ISSUE TITLE
"Add Components" labelling can be confusing

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1065]
The text "Add Components" is used both for adding items to a component list and for adding a component directly following the current one. This makes these seem like equivalent actions, though they have different results - one will add child items, the other will add siblings.

![image](https://user-images.githubusercontent.com/6829410/34003622-bfce3a2c-e0c3-11e7-9e4f-ca9fec72aa79.png)

**Comment by nelsonpecora** [comment]
Ahh, good point. @pfeytser what would you think about "Add Component After" and "Add Components Inside"?

**Comment by nelsonpecora** [comment]
Alternatively:

* "Add Component"
* "Add Children" / "Add Child Components" / "Add Inner Components" / "Add Stuff Inside"

**Comment by nelsonpecora** [comment]
Per Peter, "Add Component Below" and "Add Component Here"
