### ISSUE TITLE
Update child component affordances in single-include component lists

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1066]
There's something weird with components that include a single child component type:

* "Add Another" functionality is the same as "Add Component"
* Sometimes the Add/Dupe/Remove buttons are not shown correctly in the selector

![screen shot 2017-12-14 at 2 54 09 pm](https://user-images.githubusercontent.com/447522/34011679-e49a2896-e0de-11e7-9fe9-1b6081fd1c99.png)

**Comment by pfeytser** [comment]
Remove add component button if there is only one kind of component available.
