### ISSUE TITLE
Cannot Access "Archived"

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1071]
<img width="1375" alt="screen shot 2017-12-19 at 11 51 26 am" src="https://user-images.githubusercontent.com/4906712/34184467-ee1ff5c2-e4ed-11e7-8aa0-3a1b1f1f98ba.png">

Discovered on user's 13" laptop: on smaller laptop screens the publish pane's content extends beyond the height of the browser and the Archived dropdown is not accessible.

**Comment by nelsonpecora** [comment]
We should set a max-height on drawers, so the content will scroll
