### ISSUE TITLE
There is a delay now between clicking Publish and the content in the publish drawer appearing

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1072]
The delay is about a second, but it's noticeable.

**Comment by nelsonpecora** [comment]
That delay is from the api call to the server which publishes the page.

**Comment by pfeytser** [comment]
@nelsonpecora Is there anything we can do? Show a spinner? Load the template and later the data? Seeing the empty drawer makes me feel like it's broken.

**Comment by nelsonpecora** [comment]
Wait, you mean there's a difference between clicking the _button in the toolbar_ and the drawer appearing? That means someone recently wrote an inefficient pre-publish validator that's slowing down the app.

**Comment by nelsonpecora** [comment]
I cannot reproduce this. Do you have an example?
