### ISSUE TITLE
Comma added to value when item added to simple list

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1073]
Adding an item to a simple list and then clicking out of the field does not commit the value to the list. This is unintuitive, especially as tabbing away does cause the value to save.

Relatedly, using a comma when entering values in a simple list seems to be taken as an item separator, but is also saved in the item's value. It seems like this should either be a separator and not stored, or be stored and not a separator.

**Comment by pfeytser** [comment]
1. There are technical limitations to checking for non-added items in simple lists before closing forms. 

2. Commas should add items to list be not be included. Will fix.
