### ISSUE TITLE
Amazon dropdown menu triangle for selectors

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1077]
When hovering over to a selector from a component that is shorter than the selector, make sure the component does not unselect.

**Comment by nelsonpecora** [comment]
![](http://static.tumblr.com/9hgswys/iU1mj8c6y/bootstrap-bug.gif)

![](http://static.tumblr.com/9hgswys/vogmj8fh4/screen_shot_2013-03-06_at_1.17.35_am.png)

**Comment by nelsonpecora** [comment]
Turns out this is pretty complicated, to the point where I'm not sure if it's actually worth it.

<img width="759" alt="screen shot 2018-01-03 at 12 58 15 pm" src="https://user-images.githubusercontent.com/447522/34532889-e67687f2-f085-11e7-8261-93614d46ad69.png">
