### ISSUE TITLE
Bug: Users are unable to save changes to the layout and one-column layout components

### ISSUE THREAD

**Issue by KerenLerner** [clay/clay-kiln#1085]
Bug: Users are unable to save changes to the layout and one-column layout components

@fraddski has looked into this and believes it is not due to a missing `middle` as proposed in the first place I reported this issue:  https://github.com/nymag/sites/issues/4361 

The same error is happening on this feature branch, which has all the properties defined.  http://package-nav.thecut.sites.aws.nymetro.com/2018/01/womens-march-organizers-protest-nra-dana-loesch-ad.html?edit=true

**Comment by nelsonpecora** [comment]
What specifically is breaking on that page?

**Comment by KerenLerner** [comment]
A user is unable to save changes.

**Comment by nelsonpecora** [comment]
I cannot reproduce this locally:

1. Create a new standard article on DI
2. Add a component (masthead) to the `tertiary` sidebar (works)
3. Add a component (footer) to the `bottom` (works)

Are you able to reproduce this on a local dev environment? If so, what does the page/layout data and specific repro steps look like?

**Comment by pfeytser** [comment]
This (https://github.com/clay/handlebars/pull/48) will solve this issue.
