### ISSUE TITLE
Discussion: should users be able to backdate pages in Kiln?

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#1091]
Should Kiln be more *opinionated* about manipulating dates in published pages?

A use case to consider involves migrating an older article from another CMS into Clay and then republishing the Clay version of the article with the correct (older) date. 

In the NYMag implementation, users can add a custom date to the article. However, if the date is in the past, the publish button says "PUBLISH NOW", which is confusing. There is no clear indication of what the final date of that article is going to be.

**Comment by amycheng** [comment]
![screen shot 2018-01-16 at 2 45 33 pm](https://user-images.githubusercontent.com/1952460/35008873-f6e3e88c-facb-11e7-9047-be5f89912981.png)
![screen shot 2018-01-16 at 2 45 30 pm](https://user-images.githubusercontent.com/1952460/35008874-f6f0ff36-facb-11e7-8334-b08dedfc65e5.png)

The UI is confusing here because we have:
- the custom published date (October 2015)
- when the clay version of the article was published (1 hour ago)
- the republish now button (now)

**Comment by jonwinton** [comment]
- Publish date/custom publish date is unique to the nymag article and is used for generating feeds outside of the pagelist, which is what the Kiln UI relies on
- The Kiln UI relies on the pages index `publishTime` property, which is updated with each publish

Amphora Search is adding a property to capture the first time a page is published soon (currently in progress). The Kiln UI could be updated to reflect original publish time and most recent publish time to alleviate confusion.

Pages being imported to Clay would need to include updating the page document in Elastic to reflect this, which shouldn't be too hard to add to any import script.

**Comment by pfeytser** [comment]
We discussed this and think that backdating should be handled by the importer at the moment.
