### ISSUE TITLE
Problem: Users Are Consistently Messing Up Pages With Bad Layout Changes

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1099]
Zoe's comment in #developers:
"please be careful when scratching/editing layouts. not sure how this happened but there was a global footer above the cut footer on all cut article layouts for some length of time today and i'm not sure how it got there..."

Christian's comment in #clay-platform:
"We had our first “someone screwed up the layout level” situation post-last-fix on the cut yesterday. Zoe has the details, but they borked the footer and then added four additional dormant ads"

**Comment by cperryk** [comment]
Think it would be relatively straightforward to write a Kiln plugin to prevent changes to layout-level cmpts from being committed until the user confirms via dialog that they want to edit the layout.

**Comment by pfeytser** [comment]
We've been trying not to implement this, but it would also be good to be able check their permissions to make sure they're an admin to be able to do it at all. 

Was showing Clay to another publisher earlier this week and they were aghast at how open layout editing was.

**Comment by cperryk** [comment]
~ Notes following Slack convo ~

This is really two problems:

1. Too many people can edit layouts (devs or users, via Kiln or PUTs)
2. It's not clear in Kiln when you're editing a layout-level cmpt

Proposed solutions for each:

1. Refactor permissions system to prohibit subset of Kiln users from editing layouts and subset of devs from modifying layout cmpts (or at least require them to use a special key to do so)
2. Add friction to Kiln — e.g. confirmation dialog — in Kiln itself or via a plugin

**Comment by fraddski** [comment]
I came here to make this issue - we've had a number of layout-level additions and removals recently.

I would add that I think the template edit interface could give users false confidence when editing pages. If template editing can only be done by admin users with a large warning message at the top of the page, it seems unintuitive that a regular user could have essentially the same effect when editing any page.

**Comment by nelsonpecora** [comment]
I think we need more data before implementing changes to the permissions model. It seems to me that a lot (the majority, maybe) of these errors are due to devs sending manual PUTs to the server, which wouldn't be solved by a permissions model change (rather, it should be solved by changes to the default behavior of stuff like claycli).

1. What kinds of changes are happening? (component additions, removals, reordering, or editing)
2. Who is making these changes? (devs, product managers, designers, editorial)
3. How are the changes being made? (in the kiln UI, through scratch-cli, through claycli, or via manual api calls)

**Comment by fraddski** [comment]
@nelsonpecora I agree that there seems to be some developer error involved, I suspect through claycli, and a review of the functionality there is definitely needed.

However there were three times this month that a global header was created through the UI, and another three times a global footer was created. Six instances of the layout being messed up to this extent is significant.

**Comment by nelsonpecora** [comment]
Agreed, and thanks for the hard numbers. We're going to discuss at office hours today; are you free to swing by?

**Comment by amycheng** [comment]
I agree with @nelson that we should gather more data before changing how permissions work in Clay.

However, I also feel we can implement pieces of functionality that are smaller in scope, that would mitigate the problem of bad layout edits. Maybe these features can be worked on while permissions is being sussed out?

- Prevent layout overrides when using an importer tool. [see this commit](https://github.com/cperryk/claycli/commit/82be913f7c097a766361eba3ec7f2dcfe9c5df75) (Do our developers use `scratch-cli` or `clay-cli`?).
- Add more friction when deleting and adding to the `componentList`(?) of a `layout` component (per @byronhulcher's suggestion)
- Add visual cues to notify that the user IS editing a layout (per @reubenson's suggestion)
- Hold end-users accountable by tracking when users add/remove components (do this via GA or TrackJS?)
- Create a special api key that is just for `PUT`ing to layouts so we can track developer's layout edits

**Comment by fraddski** [comment]
@nelsonpecora I have a meeting at 3, but Amy will be there. Let me know if there's anything I can contribute to help, and if any notes/decisions come out of it I'd be keen to get an overview.

**Comment by nelsonpecora** [comment]
![img_0195](https://user-images.githubusercontent.com/447522/35695520-c369d82a-0752-11e8-9cca-b78aadb20211.JPG)

Per our meeting, it looks like the main takeaways are:

* certain components in the layout need `_confirmRemoval` enabled, to prevent their removal
* `claycli` needs to become a more robust tool, to eliminate situations where devs use `scratch-cli` (deprecated) or custom scripts to do api calls against production servers
* we should investigate [modal layout editing](https://app.zenhub.com/workspace/o/clay/clay-kiln/issues/1105) in kiln, as a longer-term way to manage layout changes
