### ISSUE TITLE
toggle-able layout editing

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1105]
From old into:

* maybe re-introduce old modal layout editing concept
* switch between editing page-specific and layout
* separate page / layout publish + unpublish
* add layouts (built-in) index (how do we know which components are layouts? are they first-class citizens, separate from components?)
* have "page history", but for layouts
* figure out how many pages a layout is used on (via adding `layout` to pages index, or something else?)

From results of investigation:

* all placeholders in _other_ mode (not the current mode) should look "disabled" (maybe like permanent placeholders?)
* placeholders (see above) and kill-links still decorate all components
* dragdrop / data-editable / selectors only decorate components in the current mode
* we should have a built-in validator that checks if a page you're about to publish has a published layout (it doesn't need to work the other way around)
* all validators should only be run on components in the specific mode (e.g. page-level when publishing pages, etc)
* add `layouts` index, with title + description (manually entered via section in publish pane), edit history, etc
* add alert when in layout mode
* make layout mode only available to admins
* change toolbar color when in layout mode (and when editing new page templates)
* Find on Page should only display components in the specific mode
* visible components should be filtered
* tabs should only display in the relevant mode
* in publish pane, page can archive + custom url
* in publish pane, layout can archive(?), add title + description

![img_0364](https://user-images.githubusercontent.com/447522/39020885-716d43c2-43fc-11e8-844d-a6771a60631a.JPG)

**Comment by nelsonpecora** [comment]
idea: have the edit/view mode picker control modal layout editing, e.g.

* View Mode
* Edit Page
* Edit Layout

Also, what visual affordances should we have for page vs layout editing?

* we tried using different colors for component selectors, which was ineffectual
* we tried using different opacity for layout components, which was way too subtle
* darker overlays make the page look weird, and disrupt the wysiwyg experience
* enabling / disabling decorators (click to edit, dragdrop, component selectors) might work, but isn't super obvious either. my worry is that the modal layout editing concept still allows people to remove things like `article` (which is in a page-specific component list), but that might not be an actual issue.
* should the layout editing be restricted to admins? it would make sense conceptually (they can edit new page templates, which affect multiple pages), though it would just be a UI barrier rather than an actual permissions barrier (PUT requests from regular users still work against layouts and components in layouts)
* should we maintain a single publish button that triggers both page and layout publishing, or should those be different when you're in different modes? this would allow finer-grained control over layout scheduling/publishing, but I'm not sure if users care that much
* do we need an edit history for layouts? it could be similar to the `pages` index, and we could add metadata like publish times, a title and description (for populating a "new layout" or "switch layouts" feature in the future), and users who've edited the layout recently

**Comment by byronhulcher** [comment]
I thought about using CSS3 blurring on un-editable components with some sort of pop-up or toast when you attempted to click into them.

**Comment by nelsonpecora** [comment]
We investigated blurring early on and it looks kinda weird, but we can revisit. I do like the toast / popover / tooltip idea though

**Comment by amycheng** [comment]
- there should be two different publish buttons for layouts and pages to really drive home that you're editing two different things. I don't think we'd need a "Scheduled layout publish" though. But maybe???
- yes layout editing should be restricted to admins. the more barriers that better! (up to a certain point)
- Maybe instead of opacity, accents, or overalys to signify the mode, we can have an additional UI element, like a pane that has a minimap of the entire layout. OR instead of a "Publish" pane, we have a "Layout Editing" pane that shows up on the left, instead of the right. The map would provide an overview of layout-level components and act as a shortcut to those components (see screenshot from Tumblr).

Questions
- what use would editors have for layout-editing history? I know WE use it to track down issues.
- is it correct to assume that there will be undo for layout edits?

**Comment by amycheng** [comment]
![screen shot 2018-04-17 at 5 16 43 pm](https://user-images.githubusercontent.com/1952460/38899002-99a34092-4264-11e8-9242-7b38c5178740.png)

**Comment by amycheng** [comment]
just adding this here for nostalgia: http://www.freecodesource.com/myspace2codes/add-html-css-codes-to-myspace-2-profile

**Comment by amycheng** [comment]
What if the toolbar at the top changes color while the user is editing layout data?

**Comment by nelsonpecora** [comment]
Per discussion:

* all placeholders in _other_ mode (not the current mode) should look "disabled" (maybe like permanent placeholders?)
* placeholders (see above) and kill-links still decorate all components
* dragdrop / data-editable / selectors only decorate components in the current mode
* we should have a built-in validator that checks if a page you're about to publish has a published layout (it doesn't need to work the other way around)
* all validators should only be run on components in the specific mode (e.g. page-level when publishing pages, etc)
* add `layouts` index, with title + description (manually entered via section in publish pane), edit history, etc
* add alert when in layout mode
* make layout mode only available to admins
* change toolbar color when in layout mode (and when editing new page templates)
* Find on Page should only display components in the specific mode
* visible components should be filtered
* tabs should only display in the relevant mode
* in publish pane, page can archive + custom url
* in publish pane, layout can archive(?), add title + description

**Comment by nelsonpecora** [comment]
Investigation and discovery on this are done, reformatted the ticket and put it in the backlog for when we start work on it.

**Comment by nelsonpecora** [comment]
Things to consider:

* [] state change (`state.editMode`)
* [] deep linking to layout editing, deep linking to components / drawers, sharing links to people without correct permissions to edit layouts
* [] alert "you are editing the "X Layout"
* [] how to apply decorators / how to quickly determine if a component is page-specific
* [] splitting the right-hand drawers (find on page / find in layout, head lists, invisible lists, publish drawer)
* [] what to do about the contributors drawer (creating a `layouts` index w/ title, users, history (note: how should amphora handle layouts?))

Decorators that should always run:

* link killer
* checksum
* iframe overlays

Decorators that should only run in active mode:

* selectors
* placeholder (active)
* component list
* focus

Decorators that should only run in inactive mode:

* placeholder (inactive)
* tooltip (on hover / click, displays a tooltip saying something like "<Component Name> is only editable in <Other> mode"

**Comment by nelsonpecora** [comment]
Per our discussion about the `layouts` index:

It needs these fields:

* creation time
* update time
* last updated user
* published
* publish time
* scheduled
* schedule time
* history (same as page)
* title

Steps to Create:

1. add `publishLayout` hook to amphora
2. add mapping, handler for `layouts` index (in amphora-search)
3. add `_layoutlist` api route to update the list from kiln
4. add simplified Layout History drawer, update publish drawer

Note that the publish drawer for layouts doesn't have archive or custom url (but does have title), and the publish drawer for pages should get a new title + authors section added (and should have layout publishing removed from the action)

**Comment by nelsonpecora** [comment]
After a bunch of research and going down different avenues, I think the best solution to the backend issues is:

* `amphora` will call the `publishLayout` hook when layouts are published (based on checking the schemas of components as they publish and finding the root `_layout` property). this will pass the user (so it works for manual as well as scheduled publish events)
* `amphora-search` will create a new document with a creation timestamp if a `POST` to `/_layoutlist` doesn't match a existing document.
* `kiln` will send updates to the update timestamp (and last updated user), un/schedule, and unpublish layouts, as well as changing the `title`

**Comment by nelsonpecora** [comment]
A few things to add:

* layouts cannot be "unpublished"
* `publish-page.vue` needs the "manually update the title/authors" section #1215 
* `publish-layout.vue` needs to call the new layout actions, remove the unpublish stuff, and add the "manual title" section
* kiln needs to fetch the layout state on load
* when fetching the layout state, if the layout isn't indexed kiln should trigger its creation
* when running validators, we need to limit the components we validate against (page vs layout)

**Comment by nelsonpecora** [comment]
Pull Requests:

* amphora https://github.com/clay/amphora/pull/545
* amphora-search https://github.com/clay/amphora-search/pull/76
* kiln https://github.com/clay/clay-kiln/pull/1230
