### ISSUE TITLE
Wysiwyg annotation 'phrase' conflicts

### ISSUE THREAD

**Issue by reubenson** [clay/clay-kiln#1107]
## Bug
When a user adds an annotation to a string of text that includes style tags, the annotation becomes segmented, as seen in screenshot.

![screen shot 2018-02-02 at 6 06 56 pm](https://user-images.githubusercontent.com/11648611/35758832-e7b4713a-0843-11e8-8884-7b71df0d7136.png)

The text resulting from this operation is as follows:
```
"Documenting <span class=\"clay-annotated kiln-phrase\">issue in which </span><em><span class=\"clay-annotated kiln-phrase\">italics</span></em><span class=\"clay-annotated kiln-phrase\"> inside of an annotation</span> breaks the annotation."
```

**Comment by nelsonpecora** [comment]
Hmm, this is due to the order of operations in Quill itself. I'm not sure if there's anything we can do about this now, but we should revisit when Quill 2.0 is released.
