### ISSUE TITLE
Timepicker does not populate input when data is saved in HH:mm format (or HH:mm:ss.SSS format for that matter)

### ISSUE THREAD

**Issue by elgreg** [clay/clay-kiln#1110]
## Bug

Kiln does not fill in the time I just chose with timepicker in the input field. The data that I saved looks like:

```
{
date: "2018-04-13T13:01:00Z",
eventName: "A great time",
url: "",
day: "2018-04-13",
time: "09:01",
timezone: "America/New_York"
}
```

but when my form presents itself, the console says:

```
clay-kiln-edit.js?version=:1 The specified value "Invalid Date" does not conform to the required format.  The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.
```

I tried saving the time field as a date format (e.g. 2018-04-13T13:01:00Z) but Kiln then just throws an error like;

```
clay-kiln-edit.js?version=:1 The specified value "09:01 AM" does not conform to the required format.  The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.
```

Thus, my form always has an empty time field, even though the data is there:

<img width="624" alt="empty_time" src="https://user-images.githubusercontent.com/40772/35897607-0a716634-0b90-11e8-86a0-8eb1d8438f30.png">

## Proposed Solution/Implementation

If timepicker values need to be stored as date-formatted strings, then shouldn't Kiln do that for me? Otherwise, can it just figure out how to parse a time as a date (e.g. adding the current day to it?)

**Comment by nelsonpecora** [comment]
Hmm, it should work if the time is specified as a string with `"HH:mm"`. I'll look into this.

**Comment by nelsonpecora** [comment]
I can't reproduce this issue. The timepicker works with strings formatted as `"HH:mm"`, while the datepicker works with both ISO8601 dates and (more useful) `"YYYY-MM-DD"`.

**Comment by elgreg** [comment]
Strange! I'll play with this some more on my end. I must be setting something incorrectly. You're using Chrome, right?

**Comment by nelsonpecora** [comment]
Yup!

**Comment by macgyver** [comment]
It's coming from the [timepicker utility component](https://github.com/clay/clay-kiln/blob/master/lib/utils/timepicker.vue#L55)  - try running this code in the console on the [date-fns docs site](https://date-fns.org/v1.29.0/docs/format)
```
dateFns.format('01:23', 'h:mm A')
"Invalid Date"
```

I'm not sure how Nelson is able to avoid the error... but it seems like the default format string should be something that conforms to the [standard for a time input value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Time_value_format )

> The value of the time input is always in 24-hour format: "hh:mm", regardless of the input format, which is likely to be selected based on the user's locale (or by the user agent). If the time includes seconds (see Using the step attribute), the format is always "hh:mm:ss".

**Comment by elgreg** [comment]
I'm curious if you go to the actual display of articleTime in your sites setup if it just says --:-- 

I can't see form the code how parsing ('13:00', 'HH:mm') would ever not be an InvalidDate

**Comment by nelsonpecora** [comment]
Hmm, maybe it's a chrome/firefox difference? Which browser are you using?

**Comment by elgreg** [comment]
I don't think so. The data stored is 'HH:mm' but running

```
>  const dateFormat = require('date-fns/format')
undefined
> dateFormat('15:02', 'HH:mm')
'Invalid Date'
```

Is always going to return Invalid Date and this line trying to mount it
looks like it's going to do that:
https://github.com/clay/clay-kiln/blob/3d3a916fbb7d6d579215aeac001135a19d8c5bc5/lib/utils/timepicker.vue#L55

**Comment by macgyver** [comment]
These are the steps we're taking:
1. save a value in a timepicker, e.g. "01:23"
2. verify the value was stored by checking the component data endpoint
3. re-open the settings form modal with the time field

**expected**: the time we just saved should pre-populate in the time input
**actual**: the time input is blank, and there is a warning in the console
> The specified value "Invalid Date" does not conform to the required format.  The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.

![timepicker](https://user-images.githubusercontent.com/1163/38326532-06b820e0-3814-11e8-8375-e7978b23679c.gif)

**Comment by Jawadban** [comment]
Yes this is happening when the hour value is < 10, its ignoring the zero before the value for some reason.
