### ISSUE TITLE
Hide extraneous "Unscheduled" and "Published" in page history

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1114]

**Comment by pfeytser** [comment]
Examples:

http://www.vulture.com/pages/cjddeltv8000m67yeq9ovxzjo.html?edit=true#

http://www.vulture.com/2018/02/the-jersey-shore-cast-is-back-for-family-vacation-april-5.html?edit=true

**Comment by pfeytser** [comment]
Need web-ops to set up ELK to debug

**Comment by nelsonpecora** [comment]
This should only be hiding `Unscheduled` events that come from the `Clay` user.
