### ISSUE TITLE
Bug: Component removal confirmation modal not appearing when deleting from the Find On Page pane

### ISSUE THREAD

**Issue by terrineal** [clay/clay-kiln#1115]
## Bug

Added a component called `amazon-onetag` and included the `_confirmRemoval: true` prop in the schema. However, if I try to delete the component from the "Find on Page" pane it does not trigger a confirmation model which is what I'd expect. If I delete the component from the page layout, a confirmation model does appear.

**Comment by nelsonpecora** [comment]
Hmm! I'll investigate this
