### ISSUE TITLE
Unable to add item to front of `complex-list`

### ISSUE THREAD

**Issue by macgyver** [clay/clay-kiln#1132]
## Bug
The documentation for the `complex-list` component reads:
```
* Items in a complex-list cannot be reordered, but can be added and removed from anywhere in the list
```

The method of adding an item to the list is either:
1. for empty lists, click "+ Add Items"
![screen shot 2018-03-09 at 15 18 57](https://user-images.githubusercontent.com/1163/37228035-475620a0-23ad-11e8-9957-3af49bdf0145.png)
1. for non-empty lists, focus an existing item and hit "+ Add Another"
![screen shot 2018-03-09 at 15 20 06](https://user-images.githubusercontent.com/1163/37228072-6535dbba-23ad-11e8-8d69-ee079a413c07.png)

It's possible to enter a new item at any offset in the list *except* for at the very start of a non-empty list. If this is desired, we should update the documentation to reflect this. If it's not desired, we should come up with some UI that permits adding new items to the start of a complex list.

The use case for this is the list of "notable links" that appear above our masthead, basically links to articles, sections, rubrics, topics, etc.. that the edit team updates throughout the day to drive traffic to various sections of the site. Their general behavior is to add new items to the front of the list (the prized spot) and let old items drop off the end of the list. 

## suggestions
Somebody suggested dragging to re-order. Maybe that would work, but my instinct is that drag and drop inside of a scrollable modal form isn't going to be a satisfying user experience. Another more lo-fi solution would be updating the "+ Add Another" button to be two buttons, "Add before" and "Add after"

**Comment by nelsonpecora** [comment]
We should update the docs to reflect this, good catch! (The reason we don't have "add before" is that it introduces a much more complex bit of code and mental model, and doesn't jive with the other ways things are added to lists (e.g. adding components, duplicating components, etc))

**Comment by macgyver** [comment]
I feel like the docs as currently written describe a more usable component.. our editors are literally copy/pasting the content of every input field for each item in the list and moving them down to the next item to shift a new item onto the front of the list.

**Comment by nelsonpecora** [comment]
Hmm, it might be worth it to explore a more Squarespace-style UI for this (and add component), since this is sort of a perennial ux issue. New users quickly learn, but the fact that it's not intuitive is not great.

**Comment by macgyver** [comment]
I might be missing something.. I find the UI to be intuitive, it just has no affordance for the desired task (shifting new item onto front of list) so the users have to execute a many-step workaround (add new entry at end of list, manually copy each field of each existing entry down by one entry, finally edit the now empty first item)

The slightly less arduous workaround I'm going to suggest is to blank the entry at the beginning of the list and **never** fill it out - so there is always a first item we can insert after. This requires template logic to strip out the blank entries, but it's preferable to the current situation..

**Comment by nelsonpecora** [comment]
Hmm, that sounds a bit hacky. Rereading your original suggestions, I think maybe having an "add before" _only on the first item_ might be the best solution. What do you think?
