### ISSUE TITLE
Modal and 'UNPUBLISHED CHANGES' inconsistencies

### ISSUE THREAD

**Issue by mcylinder** [clay/clay-kiln#1136]
_Found this while trying to diagnose why Strategist wasn't correctly setting dimension45 to reflect syndication of a product page . [Ticket](https://trello.com/c/tN5RBbH7/101-tracking-not-setting-on-original-version-of-syndicated-article)_

## Bug
There's an inconsistency in showing the UNPUBLISHED CHANGES prompt after making changes in Article Settings Modal. Changes aren't correctly set without re-publish. This maybe be contributing to confusion about an article's syndication status when it's changed but not republished.
Two different ways to reproduce the problem.

1.) If the user doesn't click far away enough from the modal. 
_Approximate red area causes the problem. Green is fine._
<img width="683" alt="modal_click_problem" src="https://user-images.githubusercontent.com/118254/37536731-d1565d78-2921-11e8-9025-81cbb2868da4.png">

2.) URL state containg "#". (edit=true# VS edit=true)

Cases when the UNPUBLISHED CHANGES modal does not remind user to republish.
...some-products.html?edit=**true#**
Change Article Settings/Syndication Status/Syndicated Source to 'Not Syndicated'
Click √ to save

...some-products.html?edit=**true**
Change Article Settings/Syndication Status/ to either 'Syndicated Source' or 'Not Syndicated'
Click green zone (in 1.) to save

## Idea
Problem 1  - might be a bubble-up event issue?
Problem 2  - is vie-router being used?

**Comment by nelsonpecora** [comment]
I'm not quite sure what you mean. Is the status not changing to "Unpublished Changes" after opening that form, making changes, and closing / saving them?

**Comment by mcylinder** [comment]
Correct. "Unpublished Changes" does not show although a change was made.

**Comment by cperryk** [comment]
@mcylinder I have a feeling what you're seeing might not actually have anything to do with article settings or where you click but rather the [30-second delay](https://github.com/clay/clay-kiln/blob/master/lib/toolbar/edit-toolbar.vue#L155) following a publish before which the edit-toolbar will not reflect further changes.

@nelsonpecora This smells like a holdover from our server.js days — do we need this delay anymore? Will submit a PR to remove if not.

**Comment by nelsonpecora** [comment]
I don't think we need this delay anymore. A PR would be super welcome!

**Comment by mcylinder** [comment]
...and it works correctly if I wait 30 seconds!! I will test after a PR and let Peter F. know about the change. It was the source of a Strategist tracking issue. Thank you!
