### ISSUE TITLE
Bug: when setting a custom url via the pane, a "Removed Custom URL" notification pops up

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#1137]

**Comment by nelsonpecora** [comment]
This needs more information before we can triage it. What was in the form, and what did you change it to?

**Comment by amycheng** [comment]
Nothing was in the form, see gif
![custom-url-error](https://user-images.githubusercontent.com/1952460/37794635-7119a8f4-2de8-11e8-875d-380df17d190a.gif)

**Comment by nelsonpecora** [comment]
Ahhhh, I think it's because you didn't begin your thing with a forward slash. We should add code to handle that.
