### ISSUE TITLE
Proposal: Add UX around Elasticsearch scopes

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#1139]
Related to [this Amphora proposal for an Elasticsearch query application layer](https://github.com/clay/amphora/issues/527). If the proposal is accepted, Kiln users will need a way to manage scopes.

* User can create and name new scopes on the page
* User can put some components into a particular scope
* User can edit the order of components within a scope
* User can remove a component from the scope to which it belongs
* Kiln removes a component from any scope it appears in when the user deletes it
* User can see which components belong to which scope
* Whenever a scope or a component within a scope is edited, Kiln updates components within a scope to reflect changes as necessary
* Kiln automatically groups "querying components" into the "default" scope

**Comment by amycheng** [comment]
what about adding a section to the pane that shows up on the right?
![img_5899](https://user-images.githubusercontent.com/1952460/37994912-ed2f9ccc-31e0-11e8-8b54-80176a08e950.jpg)

ooops forgot to add the settings icon. Just image it's there.

**Comment by nelsonpecora** [comment]
copy/pasting the potential issues/questions I had from the kickoff meeting:

* `_scope` data location and potential deduplication _(inside page data, not a problem)_
* `_scope` conflicts with keenUI _(potentially solved by putting the editing experience in something like Amy's suggestion)_
* ux / rerendering workflow and issues
* connectivity / server dependency on render _(might need a more generalized solution for all feed components)_
* scope editing ux workflow and issues _(potentially solved by Amy)_
* lack of multiquery api endpoint _(would need amphora update, and docs!)_
* save history / undo / redo issues _(might not be a huge issue, but potential race conditions if query takes too long)_
* pubsub interaction and issues _(kinda thorny)_
* user affordances and informing the user about scopes _(pretty big, but there are a few approaches that might work)_
