### ISSUE TITLE
Text format options bubble: add underline

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1146]
We're working on a component where the user needs to be able to underline text but that doesn't appear as one of the options when you highlight the text in a paragraph. 

Design we're working with:

![Screen Shot 2018-03-30 at 3.15.55 PM.png](https://images.zenhubusercontent.com/5a05f7e38a75884b9086f30a/2e254a6d-202e-4d86-9ebe-0188209fa88d)

**Comment by nelsonpecora** [comment]
Per our discussion, this is going to be solved in userland (via a `phrase` and custom styles in the parent "newsletter" component)
