### ISSUE TITLE
Bug: Simple-list can't actually save an array of strings

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#1148]
The description of the simple list input reads:

> An array of strings (or objects with a `text` property, if you add the `propertyName` argument). Useful for lists of items such as tags, keywords, or author names.

The logic for the input also [reflects](https://github.com/clay/clay-kiln/blob/master/inputs/simple-list.vue#L158) an intent to support an array of strings.

However, it's not actually possible to save a simple array of strings. No matter the field configuration or existing value, the data is always saved as an array of `{text: string}` objects. 

To recreate, add this field to the schema for a component:

```
tags:
  _label: Tags
  _subscribe: keywords
  _has:
    input: simple-list
```

Because this lacks a `propertyName` argument, based on the wording of the description we should expect Kiln to save an array of strings in this field. However, it saves an array of objects.

**Comment by cperryk** [comment]
Options:

1. Decide not to support simple arrays of strings, update the description for this input and clean up the code.
2. Decide to support strings. Modify the input code to reflect its description, opting for `{text: string}` objects only when `propertyName` is set. This would be a breaking change b/c everything currently using simple-list must be expecting objects.
3. Add a `strings` option. If `strings` is `true`, save items as strings. If `strings` is not set or `false`, save as objects. If `strings` is set but `propertyName` is also set, throw error. Provides the strings array format without causing a breaking change.

**Comment by nelsonpecora** [comment]
Yep, I thing option number 2 is the best one, but we should discuss it in person.

**Comment by olsonpm** [comment]
Could you guys explain why this was tagged `wontfix` ?  I have a simple-list without propertyName and model.save passes the data with text properties instead of an array of strings which I wasn't expecting.
