### ISSUE TITLE
BUG: Select drop-downs that are taller than the overlay are cut off

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#1162]
## Bug
Select drop-downs that are taller than the overlay are cut off and require the user to awkwardly scroll to use the drop-down. This isn't great UX
![screen shot 2018-04-06 at 4 44 00 pm](https://user-images.githubusercontent.com/1952460/38443909-55972adc-39bb-11e8-88ae-abb85f2719b7.png)

## Proposed Solution/Implementation
Not sure what the fix would be. I've tried adding `overflow:visible` to `.input-container` and `.input-container-wrapper` (defined in `overlay.vue`). This fixed this bug but caused another bug where forms that needed scrolling, couldn't be scrolled.

**Comment by amycheng** [comment]
![bug](https://user-images.githubusercontent.com/1952460/38444028-c1d881b4-39bb-11e8-89f8-3f59e6cbd0b2.gif)

**Comment by nelsonpecora** [comment]
Hmm, I thought I fixed that with https://github.com/clay/clay-kiln/commit/2ab4211f3384a11919f4cd12ded7fefa6c93bce6

**Comment by amycheng** [comment]
@nelsonpecora 

I think this is what is causing the bug:

- Kiln has no way of known how tall the expanded drop-down menu is
- ... which it needs to calculate the height ([here](https://github.com/clay/clay-kiln/blob/master/lib/forms/overlay.vue#L124) and [here](https://github.com/clay/clay-kiln/blob/master/lib/forms/overlay.vue#L291) maybe?) of the settings overlay
- this causes Settings to scroll, because the container is set to `overflow: scroll`
- changing this to `overflow: visible` fixes this bug
- ... but causes a bug in overlays that exceed the max height (like an article recirc area with lots of inputs). Overlays that exceed the max height, need `overflow: scroll`

Thinking about it now, maybe the fix involves recalculating the height when the drop-down is expanded?
