### ISSUE TITLE
Optimize New Page / Add Component / Choose Component Instance lists

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1165]
We need a unified workflow / solution for long lists of user-added templates. This would be used by "New Page," "Add Component," and (possibly in the near future) "Choose Component" (named instances / adding specific instances). Options include:

* tagging + filtering
* strict sections / hierarchies
* grouping "related" items

Page Templates we support now: 
* Article
* Homepage, section pages
* Newsletters
* Marketing pages
* Table of contents, issue archives

**Comment by byronhulcher** [comment]
Issues with "fuzzy" component lists:

Right now if a component list has `fuzzy: true` then a user can insert ANY component inside of it, including layouts, meta components, components that require specific parents, or components that are not meant for/styled for where the user is trying to add it.  This is not ideal.

**Comment by nelsonpecora** [comment]
We're still gathering requirements on this, but our initial thoughts for new pages are:

* they should allow user-created categories
* they should be sorted alphabetically
* they should still have filtering, but it matches material design's guidelines for filtering categories in lists (i.e. all categories start closed, the categories with relevant items open when filtering, then close when the filter is cleared)

![screen shot 2018-06-14 at 11 12 27 am](https://user-images.githubusercontent.com/447522/41421189-2ef41dce-6fc4-11e8-983c-20eeca60f83f.png)

For _Add Components_ (when we do "Named Instances") the UX would be the same, except that components would need a "Default" item (as the first child of the category) if they have named instances.

As for "fuzzy" lists, consensus is that it's probably worth it to remove that option from components in NYMag's Clay install where it isn't relevant anymore, while keeping it as an option in Kiln itself.

**Comment by nelsonpecora** [comment]
We need to iterate more on the Named Instances / Add Components UX

**Comment by nelsonpecora** [comment]
New Pages List broken out into https://github.com/clay/clay-kiln/issues/1251

Add Components List will not change until we decide on https://github.com/clay/clay-kiln/issues/1169
