### ISSUE TITLE
Entities (Shared Component Data)

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1171]
Components on the same page can easily share information by using PubSub, but how do components on different pages access stuff that should stay updated? We should explore shared data in a holistic sense, with the specific use cases of:

* products (updates should be reflected across all individual product components that reference the same product)
* recirc units (article data is pulled from elastic, but headline / etc overrides should be the same across different recirc units)
* images (pull from mediaplay, but the generic ones might pull from a shared source)
* listings

Our current `/_lists` sort of operate similarly (they contain shared arbitrary data) but are restricted to just arrays. We can and should have a better solution, possibly leveraging elasticsearch.

**Comment by nelsonpecora** [comment]
I want to call _all_ shared component data (lists, elastic stuff, 3rd party apis, key:val stores, etc) "collections"

As in, "This component pulls from the 'authors' collection to display author social media handles. This other component pulls from the 'published articles' collection to display the latest articles"

**Comment by amycheng** [comment]
@nelsonpecora Is there a reason why you want to call it "collections"? When I think of a "collection", I'm picturing a grouping of discrete items that are very loosely related. So, an author collection would have an array of strings with author names, an array of objects that contain social media handles, and maybe just one object that has configuration for something or another. Is this what you were thinking of?

Will there be an enforcement of data structures? Or can developers do whatever they want? Will end-users be able to edit these items from Kiln?

Also, we should probably be careful that we don't end up creating a kind of _database_ >_<.

**Comment by amycheng** [comment]
I am fond of the `data ailes` pattern found in static-site generators
- https://middlemanapp.com/advanced/data-files/
- https://jekyllrb.com/docs/datafiles/
- https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types (more complicated because it involves GraphQL)

The gist of it, is that the developer dumps `json` and/or `yaml` in a folder and can refer to that data anywhere from a page (assuming the generator is configured correctly).

I think it would neat if a Kiln developer can send a PUT to the shared data API endpoint (whatever that might be), with properly formatted JSON or YAML, and Clay automatically recognizes the data structure. 

If Clay leverages ES, someone, either the end-developer or the people developing Clay, have to figure out the mappings.

**Comment by nelsonpecora** [comment]
@amycheng re: "collections", I think there shouldn't be an enforcement of data structures, and I think those naming connotations make sense. Per the diagram below, I think the easiest way to implement these would be with two features: [collection picker](https://github.com/clay/clay-kiln/issues/1010) and [synched fields](https://github.com/clay/clay-kiln/issues/1176).

Some ideas around collections:

* Larry's doing performance testing of accessing elastic documents directly by their (primary) keys, to see if it's performant to do that on component render
* if so, we can keep components consistently updated based on the reference/elastic document key they store in their data
* we should have both _synched fields_ (for updating the collection) AND _override fields_ where necessary
* _synched fields_ that are currently hacky (e.g. authors, tags) should be updated to tell the end users what's happening
* Instead of updating a specific place, end users will be able to go to any synched component and update those synched fields to update the whole collection
* microservices and other 3rd party services may also act as collections, e.g. if we want to be able to upload images to mediaplay via Clay
* microservices and developers can sent PUT requests to any synched component _or_ update the elastic document directly to update stuff in a collection

**Comment by nelsonpecora** [comment]
So, it looks like we've got a few more features that could be a part of this, and "entities" is a better name than "collections."

![img_0365 2](https://user-images.githubusercontent.com/447522/39018635-9fd0b9e0-43f4-11e8-9113-be3bfd4d13d7.JPG)

**Comment by nelsonpecora** [comment]
Per Reuben:

The `product` component is being updated to follow something of an `entities` pattern, and I thought it might be useful to document the issue that blocked me from fully implementing the pattern, which I'm defining as the following

`
An entity is a document that lives in an elastic index, which is responsible for holding shared data props across multiple instances of a given component. When an entity-compatible component is rendered, a query to elastic is executed, and if a match is found, selected fields on the component data are overwritten with data stored in the elastic document.
`

The product component is attempting to follow this pattern, by querying and rendering results from elastic on `render`. However, I have run into a blocker due to the following chain of events:

(1) User updates the price on a `product` component from $5 to $15 and saves in kiln.
(2) On save, the redis data for the component is updated, component data is updated in elastic, and the component is re-rendered.
(3) On render, a request is made to elastic to get 'entity' data, but changes put to elastic in step (2) have not yet cleared, and the query returns the old price ($5). This old price is then rendered to the user.
(3a) If the page is refreshed, the updated price ($15) is rendered to the user.

I'm not sure where support for this would ultimately get implemented (kiln? amphora?)

**Comment by nelsonpecora** [comment]
Implementation Steps:

1. figure out prod cpu issues (in parallel, size 1)
2. implement bus (2)
3. mongo mvp (1)
4. mongo + redis cache (for published, composed data, plus uris) (5)
5. server-side schema optimization + entities (5)
6. consolidate amphora-search built-ins into mongo + pubsub (?)
7. consolidate other plugins into pubsub (?)

**Comment by jonwinton** [comment]
Closing because implementation will change once a few more Kiln/Amphora features are completed.
