### ISSUE TITLE
Feature Request: An easier way to setup a redirect to a page's canonical URL from an erroneously shared URL

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1173]
via @gloddy:

> Possible Clay Kiln feature: set up redirects after publishing.
> Scenario:
> 1. Someone shares a garbage link on twitter/fb/socail
> 2. Traffic now going to 404
> 3. They want to redirect traffic to the right place
> 4. They don’t want to delete and tweet again because the retweets and favs are already piling up
> 
> Example: https://nymag.slack.com/archives/C5UQWJ15Z/p1523889944000659
> 
> It’s happened twice in the last week, so a pretty common scenario (edited)
> and the urls are under the sites path, so it should be doable

Right now to do this with a published page someone would need to 
1) Republish at "wrong" url
2) Republish at original canonical url

Which I think is not great. So, some UX in which people could add additional URLs that would redirect to the canonical URL of a page, possibly without requiring a publish at all?

**Comment by nelsonpecora** [comment]
This might be a good feature to put into one of those sections in the publish drawer, e.g.:

```
Redirects ^

Create redirects that point to this published page. Useful when people share incorrect urls or urls with typos

/some-bad-url     X
/some-other-url   X

[text input]   [+]
```

**Comment by nelsonpecora** [comment]
Putting this in the next milestone so we can discuss and thumbs-up / thumbs-down the proposal
