### ISSUE TITLE
Synched Fields

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1176]
As part of [entities](https://github.com/clay/clay-kiln/issues/1171), we should have special fields (or rather, an `attachedButton` available to fields) that denotes that the field data will be synched to an entity rather than simply stored in the component.

Ideas around this:

* some icon that indicates the data is being shared (`↑` maybe?)
* on hover/click, a tooltip or other information saying the data is synched
* maybe some indication of where / how many places will be updated? (if that data exists in the entity)
* this same button (or perhaps a more subtle icon, but still using ↑/↓) should be automatically added (with an auto-generated tooltip) to denote when fields have `_publish` or `_subscribe`

![img_0362](https://user-images.githubusercontent.com/447522/39005322-eaa4a638-43cd-11e8-8f95-b02abb183e18.JPG)

**Comment by jonwinton** [comment]
Closing because implementation will change once a few more Kiln/Amphora features are completed.
