### ISSUE TITLE
Bug(?): Component selector is unavailable for a parent component if there is no hoverable space between it and its children

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1178]
If:

I have component A which contains a component list which can contain instances of component B
I have component B which contains a component list which can contain instances of component C
I have component C
also:
Component B is a "thin" container, with no space in the DOM which is not occupied by an instance of component C (no title or margins or anything)

In that case, I am unable to add more instances of B to A, because hovering over B I am only able to bring up the component selector for instances of C.

**Comment by nelsonpecora** [comment]
Yep, this is expected functionality. You can usually use the Find on Page drawer to access the component's settings form and add/remove/etc from there. Some components don't have settings, but that number is decreasing more and more as things like variations are added.
