### ISSUE TITLE
If `new-pages` list doesn't exist, "Add Current Page To List" doesn't work

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1182]
## Bug
If `/_lists/new-pages` doesn't exist, adding a template fails

## Proposed Solution/Implementation
If the list doesn't exist when opening the new page tab, make it automagically
-- OR --
Use an Elastic index.

**Comment by nelsonpecora** [comment]
Adding this to the entities discussion, as I think the way forward is to use a (another?!) built-in elastic index to handle the new pages list.

**Comment by nelsonpecora** [comment]
This will be handled by https://github.com/clay/amphora/issues/552
