### ISSUE TITLE
Kiln relies on border-box

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1183]
If you don't apply `box-sizing: border-box` to your elements, Kiln has some small UI bugs

**Comment by nelsonpecora** [comment]
Context: All NYMag pages have `box-sizing: border-box` applied in the layout css, so Kiln assumes this to be the case across the board. If you use a different box model, Kiln does not calculate positioning and borders correctly on its elements. Some parts of Kiln have `border-box` applied explicitly (namely, KeenUI inputs and other 3rd-party Vue components), but Kiln requires that Clay components use `border-box` so it can render placeholders and component selectors properly.
