### ISSUE TITLE
Change the toolbar publish button?

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1186]
We recently had a user who was afraid of clicking the "Publish" button in the toolbar because they assumed it would publish their page immediately. Currently that button changes based on page status, but always presents an action (Publish, Unpublish, Republish). Perhaps a noun like "Publishing" might be enough? (note that the other toolbar buttons are also action-y)

**Comment by byronhulcher** [comment]
I think a noun is a good idea. Verbs should only be for CTA's that DO something. Republish opens a whole menu of things to do.  Like "Contributors" The one outlier I think is "Find on Page" which i think sounds better than "Component Searcher" or something. But it doesn't have to be a hard rule.

**Comment by amycheng** [comment]
I wonder if this issue could be solved with more education? Have there been reports of people afraid of hitting that button?

If we change that button, it might be disorientating to other users.

**Comment by byronhulcher** [comment]
Alternatively, adding a down arrow kinda thing could indicate it opens a menu and not does an action. Maybe we do both!

**Comment by nelsonpecora** [comment]
I don't want to add an arrow for something that actually opens to the side, but I really like the "Publishing" idea, since that encapsulates more of what that drawer can do than just the verb "Publish" (or Unpublish, or Republish)

**Comment by nelsonpecora** [comment]
We're changing it to `Publishing` in the layout editing release https://github.com/clay/clay-kiln/issues/1105
