### ISSUE TITLE
Beyoncé validator should not run on URL inputs

### ISSUE THREAD

**Issue by macgyver** [clay/clay-kiln#1188]
## Bug
One legit url-slugification strategy is to deburr non-latin characters, eg. we would like this url to say "beyonce" not "beyonc" (note the missing e) https://slate.com/culture/2018/04/beyonc-brought-jay-z-solange-and-destinys-child-on-stage-for-history-making-beychella-performance.html

When we add the "e" it triggers the beyonce validator. I'm not sure it would be possible for the validator to detect slug fields.. it's just a text input with a magic button. Maybe we could update the validator to use a regexp with word boundaries around "Beyoncé" so it doesn't pick up "-beyonce" or "beyonce-"??

**Comment by nelsonpecora** [comment]
https://github.com/clay/clay-kiln/pull/1232
