### ISSUE TITLE
Feature request: custom transform functions for magic buttons

### ISSUE THREAD

**Issue by macgyver** [clay/clay-kiln#1189]
Use case: We have a different url slugification strategy than nymag, it would be nice to define our own custom transform function in our "sites" repo, similar to how the plugins for inputs, modals, etc.. work

**Comment by nelsonpecora** [comment]
This would be super useful!

**Comment by nelsonpecora** [comment]
note: let's do #1219 (trimming urls in the url transformer) as part of this
