### ISSUE TITLE
Bug: cannot command-click to duplicate in Firefox

### ISSUE THREAD

**Issue by macgyver** [clay/clay-kiln#1190]
Command key in Firefox does not trigger the "Duplicate" action ("alt" still works, but alt-clicking in macos triggers a right-click, and does not activate the button)

## Bug
![ff](https://user-images.githubusercontent.com/1163/39213080-98215978-47de-11e8-8788-2164f0c7040f.gif)

**Comment by nelsonpecora** [comment]
https://github.com/clay/clay-kiln/pull/1232
