### ISSUE TITLE
Template not updating when component list changes

### ISSUE THREAD

**Issue by KerenLerner** [clay/clay-kiln#1200]
## Bug
I have a property in my schema (`newsletter`) that's comprised of a component list with one inclusion (`newsletter-flex-text`).  When I add a newsletter then remove it, the template does not recognize that it has been removed and think the condition `{{#if newsletter}}` has been met.

**Comment by nelsonpecora** [comment]
What does the data look like at the three points?

1. before adding the child component
2. after the child component is added
3. after removing the child component

I'm wondering if maybe the handlebars `if` helper handles empty arrays as truthy.

**Comment by fraddski** [comment]
Jumping in because I was just looking at this - the first state is that the child component doesn't exist on the data at all. After removing, it's set to an empty object, which evaluates as true with handlebars.

**Comment by fraddski** [comment]
Not a component list, a child component i.e.

```
  _component:
    include:
      - svg
```

**Comment by nelsonpecora** [comment]
Is this still occurring with kiln 7.x?

**Comment by fraddski** [comment]
@nelsonpecora yes
