### ISSUE TITLE
Homepage and section page titles don't populate in page list

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1215]
![Screen Shot 2018-05-14 at 5.44.32 PM.png](https://images.zenhubusercontent.com/5a05f7e38a75884b9086f30a/6020c441-db07-4d98-8c51-fb243c8623ac)

**Comment by nelsonpecora** [comment]
The relevant components need to use pubsub to publish to `kilnTitle` and/or `kilnAuthors`, but perhaps we should add a section in the publish drawer to manually populate these?

**Comment by nelsonpecora** [comment]
It looks like some of these pages are articles, which should have pubsubbed (but may not have if someone had removed / etc the relevant components). As part of https://github.com/clay/clay-kiln/issues/1105 we're going to add a section in the Publishing drawer where users can manually enter that information (it's necessary for the `layouts` index, as well as for things like index pages)
