### ISSUE TITLE
'None' value is showing up in the componentVariation dropdown 

### ISSUE THREAD

**Issue by markerberg** [clay/clay-kiln#1222]
In the dropdown for componentVariation, the value of `none` is showing up when it shouldn't. Its populated in the list of variations. 

## Bug
No console errors are thrown but I do get this warning: 

> {kilnVersion: "6.6.1", browserVersion: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) Ap…L, like Gecko) Chrome/66.0.3359.181 Safari/537.36"} {file: "lib/forms/inputs.js"} {action: "omitMissingInput", input: {…}, _label: "WARN"} "Input "undefined" not found. Make sure you add it!"

## How I got the issue
I have three `componentVariations:` set up in my `components.yml` which point to the css. My template has `class="{{componentVariation}}`. When we click the Component Variation tab in the ui...those three variations are present but 'none' is included in that list. Its also the default value when we first navigate to that tab.

**Comment by markerberg** [comment]
@amycheng

**Comment by nelsonpecora** [comment]
@amycheng "None" is the default variation, isn't it?

**Comment by nelsonpecora** [comment]
Confirmed with Amy, "None" is the default variation
