### ISSUE TITLE
Component variation "none" option UX

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1226]
On variations the default is labeled as “none” on all components. This is making some users think that selecting "none" will strip it of all styles. 

![Screen Shot 2018-05-29 at 9.56.32 AM.png](https://images.zenhubusercontent.com/5a05f7e38a75884b9086f30a/df20748e-b381-4dc5-91fe-b95c4c665083)

**Comment by nelsonpecora** [comment]
https://github.com/clay/clay-kiln/pull/1232
