### ISSUE TITLE
Min and max for number validation doesn't work

### ISSUE THREAD

**Issue by KerenLerner** [clay/clay-kiln#1228]
## Bug
Min and max for number validation doesn't work properly.  I have the following schema property, and kiln gives me an error message about number of digits.

![screen shot 2018-05-30 at 10 22 22 am](https://user-images.githubusercontent.com/13323449/40726370-9730b866-63f3-11e8-8676-ce873a1a2453.png)

```numberOfArticles:
  _label: How Many Articles
  _has:
    input: text
    type: number
    validate:
      min: 4
      max: 8

**Comment by nelsonpecora** [comment]
Weird! We'll look into that.

**Comment by nelsonpecora** [comment]
https://github.com/clay/clay-kiln/pull/1232
