### ISSUE TITLE
Bug: New component does not have variation set

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1231]
Not sure which piece of the process is responsible here, but when adding a new component which has variations available, the recommendation is to set the component's class using `componentVariation`. This doesn't seem to be defined when a component is first created, meaning no styles are applied to a newly added component. On a refresh the property exists and classes are applied as expected.

**Comment by nelsonpecora** [comment]
https://github.com/clay/clay-kiln/pull/1232
