### ISSUE TITLE
Don't expand overlay to touch bottom of browser window

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1233]
Editors are saying that in this situation, it feels like there is more content below that is not visible.

**Comment by pfeytser** [comment]
Something like this is a little more intuitive to parse. 

<img width="1552" alt="screen shot 2018-05-31 at 12 50 23 pm" src="https://user-images.githubusercontent.com/10674066/40796072-dd59ba7a-64d1-11e8-8a67-f29ec9aa2c2e.png">

**Comment by nelsonpecora** [comment]
Hmm. Right now the skeumorphism is attempting to make it look like it scrolls off past the screen. It kinda breaks the material-ness if the material ends, but there's still scrolling stuff inside it without it moving.
