### ISSUE TITLE
change kiln link path

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1240]
Right now, kiln cachebusts itself by appending `?version={{ package.json version}}` to its script tags. Some CDNs cannot handle this, so the proposal is to have it use a different path based on version, e.g. `{{ assetPath }}/js/{{ version }}/kiln-edit.js`

**NOTE:** This would be a breaking kiln change

**Comment by pfeytser** [comment]
Query string is a standard way to do cache busting so that's what we'll support moving forward.
