### ISSUE TITLE
Reveal Not Working on QA BRanch

### ISSUE THREAD

**Issue by KerenLerner** [clay/clay-kiln#1245]
## Bug
As of a few days ago, `reveal` doesn't work on my QA branch or locally.

As you can see in the schema, there are 2 fields that should be conditionally revealed:
https://github.com/nymag/sites/pull/5171

But they don't show up in the UI when you try to edit the TV Recap component:

http://tv-recap-feed.vulture.sites.aws.nymetro.com/_pages/homepage.html

![screen shot 2018-06-12 at 3 43 10 pm](https://user-images.githubusercontent.com/13323449/41313255-78cd1e46-6e57-11e8-85b1-db64fb15ec26.png)

**Comment by nelsonpecora** [comment]
this is occurring because we're not handling non-value operators correctly in the reveal logic (e.g. when using the `falsy` or `truthy` comparator)

**Comment by nelsonpecora** [comment]
fixed by https://github.com/clay/clay-kiln/pull/1246
