### ISSUE TITLE
For array inputs, automatically set validate.required if validate.min = 1 is set

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#1247]
## Idea
For inputs that are arrays like `complex-list`, `validate.min = 1` will not trigger if the field is empty. To get the desired behavior, the developer has to set `validate.required = true`. `validate.min = 1` and `validate.required = true` are essentially the same for array inputs.

## Proposed Solution/Implementation
If one sets `validate.min = 1`, then `validate.required = true` could be automatically set to avoide confusion.

**Comment by nelsonpecora** [comment]
Keeping them separate is by design. Requiring a minimum value _if a field is set_ is different than requiring the field to be set, and that holds the same across all data types.
