### ISSUE TITLE
Scheduled Article Lists in Edit Mode

### ISSUE THREAD

**Issue by annahov** [clay/clay-kiln#1252]
## Idea
Editors should be able to sort articles by schedule date in edit mode rather than defaulting to list sort by last edited article. Articles that were scheduled but have been published should disappear from the list after publish. 

Current list view:
![screen_shot_2018-06-18_at_12 03 38_pm](https://user-images.githubusercontent.com/10500309/41548306-9013a334-72f0-11e8-8e07-0bcb0cdcdbfd.png)

## Proposed Solution/Implementation
[(optional) Have an idea about how to fix the bug you reported or the feature you just requested? Write it here!]

**Comment by nelsonpecora** [comment]
This is an interesting feature request, but I'm worried about that bug you mentioned (scheduled pages not being changed to published when publishing). Is this something you're seeing in your Clay setup?

**Comment by annahov** [comment]
On the published list, we then still see the articles as 'scheduled' after publish. Was this your question @nelsonpecora? 
![screen_shot_2018-06-18_at_12 53 58_pm](https://user-images.githubusercontent.com/10500309/41550494-ed19fc12-72f6-11e8-9ce3-88d727cf940b.png)

**Comment by nelsonpecora** [comment]
Yeah, that shouldn't be happening. Can you please create a separate bug ticket for it? (I'm not sure if it's an issue with your amphora/amphora-search config or if there's an issue in kiln)

**Comment by annahov** [comment]
Yes, thanks for investigating! Made a separate ticket here - https://github.com/clay/clay-kiln/issues/1253

**Comment by pfeytser** [comment]
Scheduled and published things should be sorted by schedule or publish time in reverse chron order automatically.
