### ISSUE TITLE
Bug: Scheduled Articles Not Appearing as Published in Edit List 

### ISSUE THREAD

**Issue by annahov** [clay/clay-kiln#1253]
## Bug
Unexpected behavior. When I got to my list of _published_ articles in the CMS, I should not see articles that have been scheduled previously included in this list. Screengrab here: 

![41548306-9013a334-72f0-11e8-8e07-0bcb0cdcdbfd](https://user-images.githubusercontent.com/10500309/41562404-7c247cc0-731a-11e8-85a9-4b8b1ef853a5.png)

**Comment by nelsonpecora** [comment]
Hmm, I'm not sure if we can replicate this locally (especially on kiln v6.0+)

I'm going to close for now, but please re-open if it's still an issue once you've upgraded.
