### ISSUE TITLE
Bug: Hover toolbar can't be clicked on linked component

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#1256]
When a component is wrapped in a link, its toolbar buttons can't be used in edit mode - the link is clicked instead.

See the "title" and "more" svgs in the tv recap feed on the vulture homepage.

**Comment by nelsonpecora** [comment]
Ah, yeah. Links interfere with kiln functionality. I'm not sure if it's documented (yet), but components' root elements cannot be links (and must be relatively positioned) for many kiln affordances to work. I want to create better documentation around this

**Comment by fraddski** [comment]
This isn't on the root element, it's in the parent component. In our case we have user-editable svg components which are the content of links. We can work around it if that's a no go, but would definitely be good to have in docs  👍
