### ISSUE TITLE
Component save/render triggered before `removeComponent`

### ISSUE THREAD

**Issue by reubenson** [clay/clay-kiln#1260]
## Bug

When deleting components, the word-count plugin lags behind the actual state of the article. For example, in the gif below, two clay-paragraphs are created. When the third clay-paragraph is deleted, the word count does not change. When the second clay-paragraph is deleted, the word count changes to the word-count corresponding to the previous state (with two clay-paragraphs).

![word-count-bug](https://user-images.githubusercontent.com/11648611/41922305-c671f7da-7932-11e8-902e-5c9bb665f428.gif)

When assessing this locally, it seemed that the underlying issue is that `state.components` passed in `RENDER_COMPONENT` on article mutation doesn't capture the delta in clay-paragraph components.

**Comment by nelsonpecora** [comment]
Hi! `RENDER_COMPONENT` happens after the state is updated, so any plugin checking state should see the correct data. As word count is a plugin, I'd advise checking its code in `sites` to see if it's considering `article` as a [component "with words"](https://github.com/nymag/sites/blob/master/global/kiln-js/plugins/word-count.js#L27)

**Comment by reubenson** [comment]
Ah I didn't do a good job of writing this issue to be more explicitly relevant to clay-kiln (and not the word-count plugin). The bug I found around relying `state.components` inside the render mutation is more general and isn't tied to logic in the word-count plugin

I've done some additional digging and debugging locally and have confirmed that when a component is deleted from an article, save & render on the article is executed _before_ the `REMOVE_COMPONENT` mutation. This seems to be consistent with how promises are chained here - https://github.com/clay/clay-kiln/blob/master/lib/component-data/actions.js#L189-L202

**Comment by nelsonpecora** [comment]
Ohh, interesting!

**Comment by nelsonpecora** [comment]
Hmm, I'm not quite sure I follow about the promise chaining stuff you mentioned. It looks like `REMOVE_COMPONENT` is happening after the save...yeah?
