### ISSUE TITLE
Page can be Published if validation fails on an input type=number

### ISSUE THREAD

**Issue by markerberg** [clay/clay-kiln#1261]
A page can be published if an input field with `type=number` fails the `required: true` validation. When we make this field empty and save the component, no errors are displayed and the page can still be published. If I manually refresh the page, the logic comes in where we're blocked from publishing until we fix that error.

**Steps to reproduce:** 

1. Find a field with type=number that's required: true and make it empty

<img width="578" alt="screen shot 2018-06-28 at 10 39 13 am" src="https://user-images.githubusercontent.com/10458251/42041447-f24f648a-7abf-11e8-9032-b9e5e91e081c.png">

2. With empty field, no red text saying 'Please fill out this field
<img width="579" alt="screen shot 2018-06-28 at 10 39 23 am" src="https://user-images.githubusercontent.com/10458251/42041465-fd76d122-7abf-11e8-909b-f28218d1e568.png">

3. Page can be published directly after saving the component
<img width="340" alt="screen shot 2018-06-28 at 10 39 36 am" src="https://user-images.githubusercontent.com/10458251/42041537-1f983796-7ac0-11e8-9bf8-f0473885b4ad.png">

4. If we manually refresh the page, the validation shows up and prevents us from publishing
<img width="328" alt="screen shot 2018-06-28 at 10 40 09 am" src="https://user-images.githubusercontent.com/10458251/42041611-40ba530a-7ac0-11e8-8503-05e70e930939.png">

> My Schema setup
```_has:
    input: text
    type: number
    validate:
      required: true
    help: Number of articles shown on a medium screen```

**Comment by nelsonpecora** [comment]
What's an example of a component with a required numerical input? I can't seem to find any.

**Comment by markerberg** [comment]
Sorry for the late response! The `latest-feed` component currently has a required numerical input. Please look at the `promoSpotPosition` field. Ref: https://github.com/nymag/sites/blob/5b4152112a034d74896881f28a2e0f0669722315/components/latest-feed/schema.yml#L49

**Comment by nelsonpecora** [comment]
fixed in https://github.com/clay/clay-kiln/releases/tag/v7.1.1
