### ISSUE TITLE
Allow ui elements inside modals to open additional modals as stack vs singleton

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1266]
The problem currently arises as a result of NY Mag's `mediaplay-picker` kiln plugin's interaction with a complex list inside of a kiln group inside of a modal.  The `mediaplay-picker` plugin is a button which can be appended to inputs which opens a modal where a user can select one or more photos.  When closing this modal using the modal's built-in close/`X` button, or by resolving the modal by selecting and inserting images, the modal closes, returning the user to the page.  If this sequence is triggered by an input inside of a kiln modal, it still returns the user to the page, rather than to the input inside of the modal. 

![modal](https://user-images.githubusercontent.com/2479295/42229488-93c8a4be-7eb4-11e8-93a6-0b2400b69267.gif)

The new `image-collection` component uses a complex list, and one of the inputs of this complex list will have the `mediaplay-picker` option. I'd like to be able to pass an argument to when I open the modal to add it to a stack instead of replacing the existing modal, so when I close out of the second modal I'm returned to the first with the complex list, so that I can continue editing.

**Comment by nelsonpecora** [comment]
One possible way we could do this is to allow modals _opened from forms_ to have a `redirectTo` property that loads the page with a specific deep link. As we add deep linking to other things, it could easily be updated to support those as well.

**Comment by nelsonpecora** [comment]
If we did deep-linking, it'd be useful to deep link to specific fields (which also ties into autofocus https://github.com/clay/clay-kiln/issues/1272). That would have to be done via the field path, e.g. (for a url field in the second item of a complex list called _content_) `content.1.url`

**Comment by nelsonpecora** [comment]
Deep-linking to fields would necessitate deep-linking to tabs. Tabs aren't covered in _any_ field path, and would have to be derived by the form itself.
