### ISSUE TITLE
Supporting Vue Templates For Components

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1270]
## Discussion
What would it take to support building components with Vue? It would be great to be able to build a Vue SPA with CLay.

**Comment by nelsonpecora** [comment]
We explored this a little in the past (when figuring out how client.js should initially work), and it's a little complicated. Most SPAs have a server-side component and a client-side component, but Clay has server-side, reader-facing, and user-facing (edit mode). If we went all-in on Vue that might be fine, but I have a few concerns:

* how do we differentiate edit-mode vs view-mode functionality?
* what subset of vue templating works server-side?
* how does our MVC-ish architecture (model.js, templates, client.js, schema) work in a 100% vue environment?
* how do we extend vue directives in a similar way as handlebars helpers?
* how do we deal with loading components? (we currently load different subsets of component templates/scripts/styles in view-mode and edit-mode, depending on the components that exist on the current page. Vue's single-file convention would break that idea)
