### ISSUE TITLE
More consistent focus on the first field of forms

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1272]
When a settings form modal is opened, and complex list is on that form with an empty input field as the first input for the first item, I'd like that input field recieve focus, as an empty text input outside of a complex list would if it was the first item in the settings form.

For settings forms with  an empty text input as the first element:
```
1) I click the settings gear or placeholder to open a settings form
2) The first panel is opened, revealing an empty text input
3) The first input in the form is focused
```

For settings forms with a complex-list containing a single empty item as the first element
```
1) I click the settings gear or placeholder to open a settings form
2) The first panel is opened, revealing a complex list with a single item with all empty fields

Expected:
3) The first input for the first item should be focused

Actual:
3) No inputs have focus
```

**Comment by nelsonpecora** [comment]
I think we need to remove the autofocus stuff from individual fields and try to implement a more top-down solution, since field-centric stuff is inconsistent at best (and creates weird focus wars when you try to use more than one nested complex-list)
