### ISSUE TITLE
Bug: Page History Sync

### ISSUE THREAD

**Issue by reubenson** [clay/clay-kiln#1283]
## Bug
`store.state.page.state` is prone to falling out of sync with changes to page. Out of sync data may then get saved to documents in the `pages` elastic index.

## Instructions to reproduce issue
(1) Import an article to production, and publish through kiln (not clay cli)
(2) Inspect the elastic document for the page that was published (e.g. http://localhost:9200/local_pages/_doc/localhost.nymag.com%2Fstrategist%2F_pages%2Fcjjswsamw01fgt6y6a3ragi83) and confirm that `firstPublishTime` is set
(3) Return to the edit page for the article (without refreshing the page), make an additional edit to the article, and re-publish
(4) Inspect the same elastic document in (2) again, which will show that the `firstPublishTime` field has been overwritten (different from the firstPublishTime observed in (2).
(5) Inspect Page History in article edit mode, which will show only a single publish event in the history, instead of two.

**Comment by nelsonpecora** [comment]
This might be fixed by amphora v7, as the `amphora-search` logic for the `pages` index will be moved into `amphora` core (as page metadata)

**Comment by nelsonpecora** [comment]
@zonika do you know if this is still an issue with kiln v8.x?

**Comment by zonika** [comment]
@nelsonpecora @reubenson it shouldn't be as kiln is now GETing the most recent page state from postgres before saving it. Elastic now listens for the save event rather than listening for a request from kiln so it should be resolved. Let me know if you're still seeing funkiness

**Comment by nelsonpecora** [comment]
Closing this per Zoe's comment, but please reopen if you're still seeing issues!
