### ISSUE TITLE
Conditionally attach buttons to component inputs

### ISSUE THREAD

**Issue by rmfarrell** [clay/clay-kiln#1289]
Related to: [Trello Ticket](https://trello.com/c/25Q5PCDx/232-2-optimize-seo-description-on-strat-w-magic-button)

## Idea
Currently, attaching a button to a component input does so universally. In order to apply a magic button to an SEO description, however, you might need to apply a specific behavior to each site.

## Proposed Solution
In the yaml file, I'd like to add a `limit` attribute that takes a grep or a URI. This would have the effect of limiting the button to appearing on pages that satisfy the grep test.

```
- name: magic-button
   component: article
   transform: autopopulateMetaDescription
   url: $SITE_PREFIX
   property: url
   tooltip: Automatically populate the SEO content with relevant shtuff
   limit: nymag.com/strategist
```

**Comment by rmfarrell** [comment]
This can be closed, right?

**Comment by nelsonpecora** [comment]
yeah
