### ISSUE TITLE
Authors with commas in their name cannot be entered

### ISSUE THREAD

**Issue by shawnswarmsolutions** [clay/clay-kiln#1304]
## Bug
When I try to enter an author name with a comma in it (for example: "Shawn Walsh, Jr." or "Shawn Walsh, Swarm Solutions"), when I enter the comma, the byline editor parses that as a complete name.

## Proposed Solution/Implementation
The byline editor should either wait for the enter key to be pressed, or offer a way to turn off splitting by comma temporarily (I can see how the use case of splitting on commas would be useful for quickly entering tags).

**Comment by nelsonpecora** [comment]
Hmm, this is a good use case we hadn't considered before. @pfeytser we should do a quick user poll / add some logging to figure out the breakdown of comma / enter / tab users in simple-lists (to determine how many people actually rely on commas when entering list items).

Alternatively, that might be an argument we pass into simple list.
