### ISSUE TITLE
Bug: Creating new component does not clone embedded component refs

### ISSUE THREAD

**Issue by reubenson** [clay/clay-kiln#1305]
## Bug
Data is cloned from component bootstrap when creating instances of a component. If named instances are referenced in the component bootstrap (e.g. ad instances in http://nymag.com/daily/intelligencer/_components/feature-ad-bundle), clones of those instances _should_ be generated for the newly created component instance. However, they are currently not being clone, and are instead being replaced with the `new` instance of the referenced component.

## Proposed Solution/Implementation
Investigation into this bug may be suggested to start here - https://github.com/clay/clay-kiln/blob/0a936aecaa73a8d50d27b4473a958a128ebae87a/lib/component-data/create.js#L217-L222, and my suspicion is that this change in an earlier PR (https://github.com/clay/clay-kiln/pull/1268/files#diff-774f79311e4d86389eef9d6d9f18c79cR217) resulted in the current behavior

**Comment by fraddski** [comment]
Any update on this? It's blocking correct placement of ads on all feature stories.

**Comment by nelsonpecora** [comment]
Sorry, this sorta fell of the radar since everyone's focused on choreographer/auth/subscription stuff. I think the earliest this could be fixed will be the beginning of next week.

**Comment by fraddski** [comment]
We _might_ be okay using bookmarking, will follow up and let you know. Also TIL, we have bookmarking!
