### ISSUE TITLE
Decorators -> Mountable Classes

### ISSUE THREAD

**Issue by rmfarrell** [clay/clay-kiln#1306]
This is a really rough proposal that I probably won't get to soon,  but I wanted to get something written down now that I'm in this section of the site. I think encapsulating this logic in classes will greatly improve the maintainability of this section.

Basically it looks like decorators are an intermediate layer between Vue and the native DOM. This is not really clear from the name, and I feel the code could be better organized with classes. Specifically a parent class `Mountable` and several duck-typed (mostly the same interface) subclasses. The subclasses have a 1:1 relationship with a corresponding Vue component that is launched when you "enter" the component. The Mountable component would otherwise have the same responsibilities they have now vis-a-vis restoring the Dom to it's original state and intelligently mounting the Vue component.

The Mountable class itself will be sufficiently general that it's easy enough for another develop to extend to any other kind of Mountable

Could also call this `Editable`

```javascript
/**
 * Options for any Mountable class.
 * @typedef {object} MountableOptions
 * @property {HTMLElement} el
 * @property {ComponentSchema} schema
 * @property {string} uri component uri
 * @property {function} mount calls $mount on the html element
 * @property {function} beforeMount called before mounting;
 * useful for inserting more info into the component
 */

/**
 * Mounts a Vue instance on an HTMLElement.
 * @class Mountable
 * @param {MountableOptions}
 * @return {Mountable}
 */
function Mountable(opts = {}) {

  // -- Interface

  // mounts the Vue instance
  function mount() { }


  // -- Internals
  function validate() { }

  return {
    mount,
    schema,
    el,
    uri,
  };
}

/**
 * Constructor for a placeholder
 * @class Placeholder~Mountable
 * @param {MountableOptions} opts
 * @return {Placeholder}
 */
function Placeholder(opts = {}) {

  const mt = Mountable(...arguments);

  return {
    mount: mt.mount,
    schema: mt.schema,
    el: mt.el,
    uri: mt.uri,
  };
}

/**
 * Constructor for a selector
 * @class Selector~Mountable
 * @param {MountableOptions} opts
 * @return {Selector}
 */
function Selector(opts = {}) {

  const mt = Mountable(...arguments);

  return {
    mount: mt.mount,
    schema: mt.schema,
    el: mt.el,
    uri: mt.uri,
  };
}

/**
 * Constructor for a Group
 * @class Group~Mountable
 * @param {MountableOptions} opts
 * @return {Selector}
 */
function Group(opts = {}) {

  const mt = Mountable(...arguments);

  return {
    /**
     * Returns Array of Editables
     * @return {Editable}
     */
    get items() { return []; },
    mount: mt.mount,
    schema: mt.schema,
    el: mt.el,
    uri: mt.uri,
  };
}
```

**Comment by nelsonpecora** [comment]
I'm not quite sure what the benefits of this approach are, especially considering the inflexibility of Classical architecture (and the lack of this pattern in other parts of the app).

**Comment by rmfarrell** [comment]
I just find this part of the repo particularly impenetrable and needing better organization. I'll come up with a better proposal if and when I have a better understanding of what is going on in general
