### ISSUE TITLE
Option(?) to move up kiln settings group modals in window

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1307]
We have a fairly elaborate UI using a complex-list where each of item has around 6-8 fields.  On a standard macbook laptop screen right now, the modal is a little cramped, and I think it could be good to give it more room.  

Here's an example:
<img width="1440" alt="screen shot 2018-08-24 at 10 23 19 am" src="https://user-images.githubusercontent.com/2479295/44590085-4207d300-a788-11e8-9ed1-8c640586a808.png">

Two options could be:
1) an option to make the settings modal go full screen universally
2) a media query checking the viewport height that gives more height to the modal when on a smaller screen

**Comment by rmfarrell** [comment]
@nelsonpecora @byronhulcher 

Sorry if this is a dumb question; I see all the logic involved in calculating the form position, but is there any issue with just vertically centering all forms in the viewport and calling it a day? 

`top: 50%;
transform: translateY(-50%)`

**Comment by nelsonpecora** [comment]
Vertically centering them (as opposed to spawning them from the point where the user clicked) feels weird in practice, especially with smaller forms). I agree that these feel cramped with longer forms (especially with complex lists), so we should explore some options to fix that.
