### ISSUE TITLE
Design bug: Static fields crash into checkbox and other static fields within group

### ISSUE THREAD

**Issue by amandliu** [clay/clay-kiln#1308]
## Issue
If there is an empty static field before a single checkbox, the fields crash visually. The issue is resolved when there is data in the static field.
This also happens when one field is empty and another has data.

<img width="408" alt="screen shot 2018-08-24 at 11 24 09 am" src="https://user-images.githubusercontent.com/15919035/44593192-be9eaf80-a790-11e8-8d27-7fcc5266d2ed.png">

<img width="571" alt="screen shot 2018-08-24 at 1 22 41 pm" src="https://user-images.githubusercontent.com/15919035/44598394-e5fd7880-a7a0-11e8-85c5-aef38756106d.png">

**Comment by nelsonpecora** [comment]
Hmm! Let's fix this asap.
