### ISSUE TITLE
BUG: Date Picker - Year Picker Not working

### ISSUE THREAD

**Issue by vicfriedman** [clay/clay-kiln#1319]
## Bug
In our current date picker, the year picker isn't working. I tested this on articles (setting a custom date) and in the space logic rules. If you select a year in the future (other than the current year), it keeps the year at the current year and doesn't update it.

**Comment by nelsonpecora** [comment]
Looks like this is a bug in KeenUI. I've [created a ticket](https://github.com/JosephusPaye/Keen-UI/issues/416) and will see if we can diagnose it / submit a PR to fix it.

**Comment by nelsonpecora** [comment]
Ah, nevermind. The year in the header doesn't change (it always shows the current year/month/day), but changing the year changes the month calendar below it:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3I3i3B2N1K1Y040p3t0T/Screen%20Shot%202018-09-07%20at%2011.45.38%20AM.png?X-CloudApp-Visitor-Id=100841)
