### ISSUE TITLE
Documentation needs a walkthrough

### ISSUE THREAD

**Issue by rmfarrell** [clay/clay-kiln#1322]
Component creation involves a lot of steps that are referenced obliquely throughout the Kiln reference but there ought to be a Walkthrough or Getting Started section for this.

**Comment by nelsonpecora** [comment]
Yup, that should go in the more generic Clay gitbook I think

**Comment by nelsonpecora** [comment]
Issue moved to [clay/clay #1](https://github.com/clay/clay/issues/1) via [**ZenHub**](https://www.zenhub.com/)
