### ISSUE TITLE
Feature Request: 'Typed' Complex Lists

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1337]
I'd like the ability to define individual schemas for different types of content I would include in a complex list, in order to lower the _complexity_ of the schema required.  Here's an existing example of a complex list schema to show what we're trying to achieve:
https://gist.github.com/byronhulcher/3f1ce3da5da2733ab34e8142e9b33f1c

As you can see, we have to have a lot of repeated logic for the `_reveal` and `validate` properties keyed on the `type` prop.  There are many shared fields between components (remark + related link) but also fields unique to these types (quick-chat, tweetUrl)

I think it would be better if I could define some types for my complex list, where stuff like reveal and validate logic is only relevant to them, along with an auto-added "type" dropdown (similar to how we automatically insert a "variation" dropdown without requiring it be added to a schema).  This would go a long way towards improving the readability and maintainability of this schema going forward!

**Comment by rmfarrell** [comment]
@byronhulcher How would you feel about a javascript API?

**Comment by byronhulcher** [comment]
Ideally I’d be setting this up in the schema.yml along with the rest of my
component data I think

**Comment by byronhulcher** [comment]
@rmfarrell oh okay cool! The important thing to me is that this would live wherever the rest of the kiln logic would live, so if that's moving to a JS api eventually, then its fine with me if this is moved along to there as well 😎
