### ISSUE TITLE
Page Menu Plugin API Affordances

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1345]
## Idea
Open up the plugin API to add buttons to the page list

![screen shot 2018-10-10 at 12 15 39 pm](https://user-images.githubusercontent.com/4906712/46750632-5c3d3800-cc86-11e8-9bfc-21a9c8b25a32.png)

## Proposed Solution/Implementation
Plugins should be able to add a button in the left column, either in the top section or bottom section.

**Comment by nelsonpecora** [comment]
Context: Similar to how we allow plugins to add buttons to the component selectors and the toolbar, we should allow them to add menu items to the Clay Menu. These would sit beneath "New Page" and above "Users"/"Sign Out", and the plugins could choose if they should be usable by all end-users or only admins.

Note that the mobile Clay Menu might need to be redesigned slightly to support this additional functionality.
