### ISSUE TITLE
Feature Request: Force component to run model.save on server

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#1349]
I'm running into an issue with an instagram embed component which takes a URL and hits instagrams oembed API.  At some point recently, they began attaching a `content-security-policy` header to responses to this endpoint, which forces Chrome and Firefox to block them (hooray CORS!!!!!!). This endpoint works fine if accessed from the server, I'm able to successfully save the component when manually PUTing the url through something like Postman.  It's only blocked within the browser with kiln.

I'd like the ability to mark a component in some way that clay-kiln will _always_ save it through the server, and render the results.  I know this is less than ideal and would cause the UX to be slow but... its better than a component being unable to save completely.

**Comment by nelsonpecora** [comment]
Most components (specifically embeds) get around this by doing a JSONP request with a fake callback (see `services/universal/rest.js` in the NYMag Clay instance)
