### ISSUE TITLE
Permalink plugin drawers

### ISSUE THREAD

**Issue by rmfarrell** [clay/clay-kiln#1377]
## Idea
drawers should be permalinked

Specific need: the Pyxis drawer is likely going to bookmarked by some users & triggering a page load should keep the drawer open.

The ability to implement an internal subrouter on drawers would be even nicer since this one has multiple views.

**Comment by jonwinton** [comment]
This can be broken down into two steps:

1. Allow plugins in the Clay menu to be linked to
2. Add deep linking to other Kiln drawers/panes

**Comment by rmfarrell** [comment]
word. Don't want to overengineer this. A hash setter and hashchange listener should be fine.

**Comment by scottnash** [comment]
There is a hash setter in there now.  Just navigate your way in kiln to somewhere you're editing a component and you'll see the hash change to something like: 
 #manual-article~cjpyk3ff5000o3k5zdadqx3xx~teaser
which is made up of: `${component}~${instance}~${path}~${initialFocus }` 

Or open the clay menu and click on All Pages and you'll see the hash become
 #kiln~all-pages~nymag~all
`#kiln~${tab}~${sites}~${status}~${query}`

It differentiates between the two by checking the hash.split('~')[0] and if it matches 'kiln' then it assumes the hash is for the clay menu.

We could open that #kiln~ version so it doesn't automatically open the clay menu (which is what happens now even if you make the hash #kiln~blah-blah) and instead could apply to anything that wants to react to it. So it could be #kiln-pyxis and the pyxis plugin could respond however it wanted.

**Comment by rmfarrell** [comment]
that sounds reasonable

**Comment by scottnash** [comment]
https://github.com/clay/clay-kiln/blob/master/docs/deep-linking.md
