### ISSUE TITLE
Memo Url Value Bug

### ISSUE THREAD

**Issue by TTaitFoster** [clay/clay-kiln#1406]
In order for Memo to be implemented correctly, the url value passed to us must match the canonical value for the article. On three of your domains (Grubstreet, NYMag, Strategist), there is no issue. 

However, on two of your sites (The Cut, Vulture), the sites are on https protocol, but we are being passed the http protocol in the canonical value. 

![image.png](https://images.zenhubusercontent.com/5bff0b7bc933760fceec71ab/00bfd09a-03e2-4fd1-bb24-08b7be1c483f)

**Comment by jonwinton** [comment]
@TTaitFoster that's an issue with the memo component specifically, not Kiln. The value from there is pulled from `locals.publishUrl` (if I recall correctly), but NYMag's publish rules aren't setup to handle publishing to https urls. This is a known issue which has other consequences (with Elastic data, for example).

**Comment by scottnash** [comment]
@jonwinton is correct, although he should really be getting a life instead of commenting on Clay tickets, 3 days after leaving!!!! 😄

**Comment by TTaitFoster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Memo URL bug](https://trello.com/c/WuTHTTxM/100-memo-url-bug)
