### ISSUE TITLE
Update keen-ui

### ISSUE THREAD

**Issue by scottnash** [clay/clay-kiln#1426]
Keen-ui hasn't been updated lately (apart from one bug fix).  Should be updated to take advantage of changes.  According to version numbering, there haven't been any breaking changes, but would still need to be tested carefully before releasing.  Don't want to break any plugins because of updates.

**Comment by TTaitFoster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update keen-ui](https://trello.com/c/iozjOMcS/111-update-keen-ui)

**Comment by scottnash** [comment]
See https://github.com/clay/clay-kiln/issues/1446
