### ISSUE TITLE
kiln.js add fetch custom events that returns data with caching

### ISSUE THREAD

**Issue by scottnash** [clay/clay-kiln#1428]
RIght now you can make api calls using kiln.js by using vanilla.js, but would be good to add a built in kilninput.fetch function that would include caching, timeout options, failure options, etc.

**Comment by TTaitFoster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kiln.js add fetch custom events that returns data with caching](https://trello.com/c/V4tHjxVw/112-kilnjs-add-fetch-custom-events-that-returns-data-with-caching)
