### ISSUE TITLE
Kiln.js should be able to use custom validators

### ISSUE THREAD

**Issue by scottnash** [clay/clay-kiln#1433]
When using schema.yml files to construct components you can use the custom validator files for field validation.  Kiln.js should also be able to use those files.

**Comment by TTaitFoster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kiln.js should be able to use custom validators](https://trello.com/c/WA4q8MBf/113-kilnjs-should-be-able-to-use-custom-validators)
