### ISSUE TITLE
Add functionality to the magic button behavior to look at multiple fields or components for data

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#680]
It would be useful if the `magic-button` behavior could look at another field or component for data if the initial field/component is missing

## Use Case:
- `lede-caption` looks for data in the first `lede-feature` component, it would be great if it could also look for data in the first `lede-full-bleed` component, if `lede-feature` is missing

**Comment by nelsonpecora** [comment]
Hmm. This is a valid use case, but I'm not sure how we'd specify the arguments. @amycheng any ideas?

**Comment by amycheng** [comment]
@nelsonpecora I imagine it could be an array. So `targetComponents: ['lede-feature','lede-full-bleed']`

One snafu, is that behavior looks for the `[rv-field="${field}"]` selector, and some components don't   use that selector (ie authors).

**Comment by nelsonpecora** [comment]
Lemme add this as a feature request for v1.0, so we don't need to worry about `rv-field` stuff :-)

**Comment by nelsonpecora** [comment]
Another good example for this is the article slug (which should pull from `seoHeadline` or `shortHeadline`

**Comment by nelsonpecora** [comment]
The 4.0 release is pretty big already, so I'm bumping this to 5.0

**Comment by nelsonpecora** [comment]
Ok, this will be added to the 5.0 release. The configuration remains the same as before, except that now `field` and `component` can accept either a string (old affordance) _or an array of fallbacks_
