### ISSUE TITLE
Keyboard Shortcuts - Top and bottom of paragraph and document

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#841]
The user in the test was referring to common word processor shortcuts: 

⌘ + ↑ = go to top of document
⌘ + ↓ = go to bottom of document
Option + ↑ = go to top of previous paragraph
Option + ↓ = go to bottom of next paragraph

**Comment by nelsonpecora** [comment]
Closing this in favor of just using native shortcuts with content-lists
