### ISSUE TITLE
minor: use asyncComputed in autocomplete.vue

### ISSUE THREAD

**Issue by mheiber** [clay/clay-kiln#854]
when @mheiber added list-getting to `autocomplete.vue` he used `computed` instead of `asyncComputed` which leads to this ugly `if`:

https://github.com/clay/clay-kiln/blob/master/behaviors/autocomplete.vue#L50

TODO: use `asyncComputed` like in `people.vue`:

https://github.com/clay/clay-kiln/blob/master/panes/people.vue#L114

**Comment by nelsonpecora** [comment]
fixed in commit 6a98b93
