### ISSUE TITLE
Tags - bottom component selector looks weird

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#855]
There's an empty space at the bottom

![screen shot 2017-05-19 at 3 38 38 pm](https://cloud.githubusercontent.com/assets/10674066/26264066/6b352890-3ca9-11e7-9940-3652c43457d7.png)

**Comment by nelsonpecora** [comment]
Ahh, tags' selector looks weird because it has no icons. Let me see if there's a quick fix
