### ISSUE TITLE
After Combining Paragraphs Cursor In Wrong Place

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#856]
After clicking backspace, the cursor appears several spaces to the left of where the combine happened. 

<a href="https://dl.dropboxusercontent.com/s/eniyf2844828d5h/83123046-E46A-4EBD-931E-C5061ECC0C6C-13224-000013C110699B73.gif?dl=0">See GIF</a>

**Comment by nelsonpecora** [comment]
I can't reproduce this issue. What's the text you had in each paragraph? (It might be some subtle bug with how we count caret position when merging, which isn't the cleanest code

**Comment by nelsonpecora** [comment]
I think I may have fixed this in Kiln v3.3.4
