### ISSUE TITLE
Extra click needed when new paragraph is created

### ISSUE THREAD

**Issue by gloddy** [clay/clay-kiln#857]
Repro steps:
1. Type in a paragraph
2. Hit enter twice
3. New paragraph created
4. Now I have to click in paragraph to start typing

Expected result:
I should be able to type in the second paragraph immediately after the second enter.

**Comment by pfeytser** [comment]
@nelsonpecora Just tested this feature, behavior is unchanged for me.

**Comment by nelsonpecora** [comment]
By "behavior is unchanged", do you mean it's working or broken? :p
