### ISSUE TITLE
lists: don't re-fetch every time

### ISSUE THREAD

**Issue by mheiber** [clay/clay-kiln#863]
maybe I shouldn't have [recommended asyncComputed (see #854 )](https://github.com/clay/clay-kiln/issues/854) .

![screen shot 2017-06-09 at 5 35 11 pm](https://user-images.githubusercontent.com/4691093/26995334-09945894-4d3a-11e7-9834-000bb770d13b.jpg)

The list gets requested every time the user click the instance of the simple-list behavior, but we stuck lists in the store to *avoid* requesting them every time.

Sorry!

**Comment by nelsonpecora** [comment]
Hmm, point. Let's see what I can do about this.

**Comment by nelsonpecora** [comment]
fixed in 5.0.0. It'll only fetch the first time an autocomplete opens pointing to a list (since that list won't exist in the store yet)
