### ISSUE TITLE
Feature Request: Generic `site-specific` behavior

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#865]
We already have a behavior like `site-specific-select` but it would be great if this was abstracted so I could apply it to other behaviors who could have arguments specific to eat site, for instance `checkbox-group`. This way one would not have to create seperate instances of behaviors like `site-specific-checkbox-group` which would have to be maintained in parallel.

**Comment by nelsonpecora** [comment]
Might be neat! I created a ticket in our backlog to discuss: https://trello.com/c/rq3kJAbn/62-generic-site-specific-kiln-behavior
