### ISSUE TITLE
add operator to reveal behavior to test for values of an object

### ISSUE THREAD

**Issue by reubenson** [clay/clay-kiln#866]
In the case when a component has a property that is set to an object, it would be useful to be able to hook reveal behavior on the key-value pair in that object. For example, in the article component, the magazine issue date should only show when 'New York Magazine Story' is selected as a feature type

**Comment by nelsonpecora** [comment]
note to self: this is generalizable for checkbox-group and such behaviors

**Comment by nelsonpecora** [comment]
fixed in commit 39517b9
