### ISSUE TITLE
Validation error messages for "pattern" in schema.yml

### ISSUE THREAD

**Issue by mheiber** [clay/clay-kiln#873]
# Current Behavior

When providing a regex for a property in schema.yml, there's a generic error message "Please match the requested format".

# Expected behavior

Enable us to specify a meaningful error message in the schema.yml so users can know how to correct their entries

**Comment by nelsonpecora** [comment]
Validation messages are...complicated, and not very consistent across browsers. It's possible to do this, but we'd have to think through all the scenarios. e.g. is there a single message specified in the schema, or different ones for different invalid states (type set to url but different input, pattern mismatch, required stuff that's empty, etc etc)

**Comment by nelsonpecora** [comment]
I'm gonna close this for now, but please reopen if you've got ideas around this.
