### ISSUE TITLE
Amphora Peer Dependency Management

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#876]
How can we provide more information about peer dependencies between Amphora/Kiln/Amphora Search? 

We could do the same thing with `_envVars` and send across versions for plugins, renderers and Amphora itself, but then what could Kiln do with that info to help with proper dependency management/upgrades?

**Comment by nelsonpecora** [comment]
Hmm, what's the deal with npm peerDependencies nowadays? I heard they were removing it, then adding it back, then ????

**Comment by nelsonpecora** [comment]
I think we can deal with this simply by communicating well in the changelog
