### ISSUE TITLE
feature request: be able to add different options(value?) AND labels

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#879]
right now, Kiln automatically generates a label from the option listed in the schema but there might situations where the radio button needs to have a label is different from the value.

**Comment by nelsonpecora** [comment]
Yes! I want to get `checkbox`, `select`, and `radio` standardized on the new site-specific-supporting format (namely, `options` being an array of strings _or_ objects, with the same properties and logic across all of those behaviors). Let's slate this for the next major version.

**Comment by nelsonpecora** [comment]
Behaviors that need to be consolidated

* [x] checkbox-group
* [x] select
* [x] radio (add site-specificity, allow array of objects)

**Comment by nelsonpecora** [comment]
Looks like we just had to add site-specificity to `radio`. Done in commit f9b4a34
