### ISSUE TITLE
[Kiln 3.6.0] Pub/sub doesn't subscribe when getting values from 2 components

### ISSUE THREAD

**Issue by meijioro** [clay/clay-kiln#885]
I did some QA for the pub/sub functionality and I found some bugs.

### What it did fix :thumbsup:
It does fix 2 components on a page being able to subscribe to the same `_publish:` id.

## Testing
I made 4 test components.

[testfile](https://github.com/slategroup/slate-redux/tree/testPubSubFix/components/testfile)
- A simple component that only subscribes to one `_publish`.
- For comparison purposes since this always works :+1:

[testfile2](https://github.com/slategroup/slate-redux/tree/testPubSubFix/components/testfile2)
- Subscribes to `articleImage` from `slate-image` component
- Subscribes to `rubric` from `article`component
- To show what happens when you subscribe to two different publish ids that come from two different components.
- Doesn't work :no_entry_sign:

[testfile3](https://github.com/slategroup/slate-redux/tree/testPubSubFix/components/testfile3)
- A simple component that only subscribes to one publish id.
- To test if two components on the page that subscribes to the same `_publish` works.
- Works (it was broken pre 3.6.0) :+1:

**Subscribed values and where to find them** 
[rubric](https://github.com/slategroup/slate-redux/blob/testPubSubFix/components/article/schema.yaml#L247)
[articleImage](https://github.com/slategroup/slate-redux/blob/testPubSubFix/components/slate-image/schema.yml#L5)

### Test 1
- I added an image to the `slate-image` component and the path shows only for a split second in test box 2 before disappearing. You can see the screen capture of it the example video (keyframe it to 00:00:04) Example: [testA.mov.zip](https://github.com/clay/clay-kiln/files/1174528/testA.mov.zip)

### Test 2
- However, if I add the `rubric` in `article` first. Then update `slate-image` after then you'll see both values render fine. [Example](https://dl.dropboxusercontent.com/s/fqb0hhzkll0zi2r/4A50714A-1F1E-4D2A-822C-6A66D9160ECE-42213-000324EF2ABD7929.gif?dl=0).
- I also did notice when I looked at the instance (I ran start-local, gulp, & scratch). I only saw `rubric` and no `image`.

**Comment by nelsonpecora** [comment]
It looks like (in Test 1) your article is being triggered by `articleImage` (which `fallbackFeedImgUrl` subscribes to), which is causing it to save and publish something else (the rubric?) but that's triggering a second save in testfile2. I'm not sure why the image url isn't there the second time testfile2 saves, because it should be waiting for the full save to be complete before the second one fires.

**Comment by nelsonpecora** [comment]
Hmm, I'm trying to replicate this but it looks like testfile1 and testfile3 have the same schema...?

**Comment by meijioro** [comment]
Yes but `testfile3` isn't the problem. That yes just to test the scenario of having two components on the page subscribing to the same publish id. That works and you can not pay attention to it at all. 

The bug is with `testfile2`. I've tried testing with subscribing to different publish ids from different components and it still ends up not working.

**Comment by nelsonpecora** [comment]
@meijioro Is this still an issue? I was never able to reproduce it

**Comment by meijioro** [comment]
Hmmm, I'm guessing upgrading to Amphora 3 fixed this bug.
