### ISSUE TITLE
Settings pane does not scroll upon second opening

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#886]
The settings pane does not scroll after the first time it opens and closes.

To reproduce:
* Add a component with a long set of properties to a page.
* Open the settings pane for that component. Scroll should function as expected.
* Close the settings pane.
* Open the settings pane for any component. Scroll will not function as expected.

[Example](http://stg.www.thecut.com/pages/homepage.html?edit=true) (try basically any component on this page)

**Comment by nelsonpecora** [comment]
There are a bunch of little edge-case bugs around scrolling / resizing / fixing the height of panes, so the platform team is going to discuss redesigning them a bit so they aren't dynamic height anymore https://trello.com/c/MMpif9jA

**Comment by cperryk** [comment]
@nelsonpecora OK, thanks. If there's a quick way to circumvent on my end, let me know. QA of all homepage components is blocked until we resolve this.

**Comment by cperryk** [comment]
@nelsonpecora Actually, scratch that. I'll instruct people to just refresh until this is resolved. But let me know if you see a way around it for now.

**Comment by nelsonpecora** [comment]
fixed in https://github.com/clay/clay-kiln/releases/tag/v.9.0
