### ISSUE TITLE
BUG: Field with no applicable site-specific options will still have its label and description show up

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#887]
For example, a `storyCharacteristics` field only has options available for Site A (no defaults should be set). However on Site B, the user will still see the label and description for `storyCharacteristics` but no options to select.

My proposed solution is that Kiln checks is there are options available for the site, if there are no options, then Kiln should apply a class to hide the field (like `.kiln-reveal-hide` found in the `reveal` behavior).

**Comment by nelsonpecora** [comment]
This is expected functionality, as a `select` with no options is a programmer error. Behaviors can only reach up to fields in very specific circumstances, such as `reveal`.

**Comment by nelsonpecora** [comment]
I get what you're going for, but I think the proper way to do it would be to expand the functionality of the `reveal` behavior so that it could check what site you're on. @amycheng what do you think?

**Comment by nelsonpecora** [comment]
I'm actually gonna keep this ticket open because the `select` and `checkbox-group` behaviors should display a default message ("No options available on this site") if there are no available options.

**Comment by amycheng** [comment]
Using `reveal` is fine by me, but what happens if the data I want to check against is not accessible? Displaying a default message also works for me.

**Comment by nelsonpecora** [comment]
`reveal` updates → https://github.com/clay/clay-kiln/issues/888

**Comment by nelsonpecora** [comment]
![screen shot 2017-07-26 at 5 06 30 pm](https://user-images.githubusercontent.com/447522/28643741-d87a1e1e-7224-11e7-8610-264362514bf8.png)

When there are no options, it'll look like so.

**Comment by nelsonpecora** [comment]
added in https://github.com/clay/clay-kiln/releases/tag/v3.8.0
