### ISSUE TITLE
Delete Tag Triggers "Back" in Firefox

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#892]
To repro in Firefox: 

1. In Kiln click on a tag so it's highlighted blue.
2. Type delete.

**Comment by nelsonpecora** [comment]
Does this only happen in Firefox (also, what version(s))? Those tag elements should be focused, but Firefox might not be preventing the default event handler when you hit delete.

**Comment by nelsonpecora** [comment]
fixed in kiln 5.0.0

**Comment by uiuxdesigner3** [comment]
<a href="https://qaabildigital.com/ui-ux-design-service.php" rel = "Dofollow" > UI UX designer </a> is crucial to just about everything. It renders the latest technology accessible to the masses, makes our favourite apps and websites a pleasure to use, and determines which brands and products we return to over and over again. To put it simply, design matters.
