### ISSUE TITLE
idea: migrate from dragula to sortable.js

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#904]
* we're currently using a custom version of dragula because of the [deadzone PR](https://github.com/bevacqua/dragula/pull/379)
* we've had to re-implement a lot of functionality like scrolling and custom drag handling
* dragula doesn't handle multiple lists (e.g. dragging an image from a subsection to an article) or multi-dimensional dragging (e.g. simple-list reordering)
* there's a vue component that easily implements sortable.js → https://github.com/SortableJS/Vue.Draggable

**Comment by nelsonpecora** [comment]
[trello discussion](https://trello.com/c/oWMHXvGy)

**Comment by pfeytser** [comment]
Expose sortable on the window for plugins.

**Comment by nelsonpecora** [comment]
Example of current dragdrop

![drag_and_drop_related_stories_is_hard.gif](https://images.zenhubusercontent.com/5285493dc80459a430000008/e161a737-5579-4d58-885c-2afcecf8a52b)

**Comment by nelsonpecora** [comment]
I think we should discuss mobile scrolling / dragdrop issues before I do this

**Comment by nelsonpecora** [comment]
Investigation (#1037) is complete. We should switch to sortable.js, and use a 100ms delay (rather than a pixel deadzone) to solve both the clicking-into-things issue and the mobile scrolling issue.

**Comment by nelsonpecora** [comment]
Some notes from editor / writer feedback:

* dragged items should scroll when you get close to the edge of the viewport (sortable does this)
* current ghost positioning gives incorrect positional heuristics (sortable should fix this)

**Comment by nelsonpecora** [comment]
Context: We use a custom fork of Dragula to do drag-and-drop functionality, as we wanted to allow some sort of "deadzone" before drags are initiated (many users move their cursor a small amount when tapping/clicking on things, and the default Dragula parameters consider that a drag rather than a click, leading to a lot of erroneous drags). Moving from our custom Dragula implementation to Sortable (and switching from a pixel-based "deadzone" to a time-based one) would solve for this use case _and_ solve for the "mobile scrolling issue" (in short, dragging with your finger is how you scroll on mobile, so there needs to be some kind of timeout to differentiate it with initiating drag-and-drop)
