### ISSUE TITLE
Hover cursor applied to editable components outside of edit mode when logged in

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#911]
When viewing a page while logged in, but NOT in edit mode, moving the mouse cursor over a component will cause the mouse cursor to go into "pointer" mode.  

For instance on http://www.vulture.com/2017/09/dylan-obrien-is-back-from-the-brink.html while logged in, pointer mode for the mouse cursor could be visible if the cursor is in the whitespace of the feature lede, or in the margin between paragraphs. Viewing the page in Incognito Mode, while logged out, does not trigger this behavior.

I'd include screenshots but I can't figure out how to do that and include the mouse.

**Comment by nelsonpecora** [comment]
fixed in kiln 4.x
