### ISSUE TITLE
idea: Ability to copy the data from one instance on a page to another instance of same component

### ISSUE THREAD

**Issue by ashwu** [clay/clay-kiln#913]
For example, if a `clay-subheader` component on a page has per instance styles, the [+1] button could add another subheader with the same styles and only the text would need to be changed.

Use case: Vulture's New on Netflix (and amazon, hbo, etc) needs a refresh and we're designing some subheaders to go in, but it's tedious to have to copy/paste the same styles for new instances of the same component.

**Comment by nelsonpecora** [comment]
We debated this when we added the "duplicate" functionality, and I can see both sides of the argument. Ideally, I'd like to have something like:

`cmd + click` → `+1` → duplicate component with default data (basically add a new instance of the same component)

`cmd + shift + click` → `duplicate icon` → duplicate component with data from current

How does that sound? The only issue I can see is that this might not be super discoverable (maybe we could tie it to admin accounts, or have a tooltip explaining what's up, or something like that)

**Comment by pfeytser** [comment]
Add separate button to duplicate component. 

On meta key, duplicate the component with data.

**Comment by pfeytser** [comment]
QA Acceptance Criteria

- There is a new "duplicate component" button on the component selector. 
- When I hold Ctrl or Cmd, the duplicate button turns into "duplicate with data"
