### ISSUE TITLE
Kiln ignores some component keys with no warning

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#914]
Discovered this while trying to figure out why selectors were not being added to components in a component list. After some investigation I determined that it was because the component list property name was `media`, which Kiln [ignores](https://github.com/clay/clay-kiln/blob/master/lib/utils/deep-reduce.js#L16) when traversing the component tree.

Not sure why we've reserved these properties or if they need to be here anymore. At the very least, there should be some kind of console warning if a component schema includes them. Happy to submit a PR once I have an understanding of the best approach.

**Comment by nelsonpecora** [comment]
Ahhhh, these are root-level (and component-level) keys that are used when the fully-composed page data is sent to kiln (on page load). Thanks for finding this! I need to split these out into things that the kiln preloader should ignore (media, sites, etc things in the page) vs things that all components should ignore (_ref, locals)

**Comment by nelsonpecora** [comment]
fixed in https://github.com/clay/clay-kiln/commit/83e363794a4dfe260df8e2626f649df4e7d85132
