### ISSUE TITLE
Bug: Registering the addOrdinalSuffix helper

### ISSUE THREAD

**Issue by terrineal** [clay/clay-kiln#919]
## Bug
Would like to have the `addOrdinalSuffix` helper in `nymag-handlebars` added to `clay-kiln`. Currently, I'm getting the following error when I add a component that uses the helper: `clay-kiln-edit.js:20 Error saving component (congress-tracker-table): Missing helper: "addOrdinalSuffix"`

**Comment by nelsonpecora** [comment]
👍  updated in kiln v4.5.1
