### ISSUE TITLE
`customUrl` has semicolon in PUT request

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#925]
## Bug
When a `customUrl` is saved for a site running on port 80, the `customUrl` field is being sent with a `:` after the site's prefix. `http://somexample:/custom/url.html`.

**Comment by nelsonpecora** [comment]
is it only customUrl, or everything? Since this uses the same site prefix handling as all the other api calls

**Comment by jonwinton** [comment]
I've only seen it on `customUrl`

**Comment by nelsonpecora** [comment]
Alright. I'm gonna close this for now, but please re-open if you encounter this in kiln 5.x
