### ISSUE TITLE
Bug: WYSIWYG link entry breaks link fragments

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#926]
## Bug
Kiln currently forces all links entered in the WYSIWYG editor to include a protocol of http or https, which does not support a number of valid link formats, including link fragments. This logic should use a whitelist to allow link fragments (e.g. `#subsection`), and other commonly supported protocols such as `mailto` and `tel`.

**Comment by nelsonpecora** [comment]
This is fixed in kiln v4.6.1 https://github.com/clay/clay-kiln/releases/tag/v4.6.1
