### ISSUE TITLE
BUG: certain unicode characters are breaking Kiln

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#929]
## Bug
Unicode characters such a `\u2028` and `\u2029` are being pasted from Word and are ending up in component data. This causes Kiln to break. 

## Proposed Solution/Implementation
- add sanitization (like this [logic](https://github.com/clay/clay-kiln/blob/master/behaviors/wysiwyg-paste.js#L77) to the `text` behavior). These characters are being removed properly in forms with the `WYSIWG` behavior but no where else.
- figure out a way to completely ban these characters from Kiln?

**Comment by byronhulcher** [comment]
IMO we could also strip these from https://github.com/clay/clay-kiln/blob/f06fddc14e87c771f8a7c3a4314eb5a1b1b1c747/template.handlebars#L26, in case these come from a different source than kiln (like an import).  This line specifically is where Kiln is throwing an error.

**Comment by amycheng** [comment]
well having sanitization happen in the text behavior prevents the bad data from being _saved_ but during preload it will prevent the bad data from being _rendered_ so should it happen in both places? Or will the `upgrade.js` cover the first case? 🤔

**Comment by amycheng** [comment]
actually we can just sanitize the preload data. There might be cases that we'd want to keep those unicode characters/line breaks in the rendered text. 

but why would unicode break the template in the first place? 🤔🤔🤔

**Comment by amycheng** [comment]
@byronhulcher Can you copy and paste the error that Kiln/Amphora is spitting out? I'm wondering if the bug is a Handlebars compilation error or something else.

**Comment by byronhulcher** [comment]
I'll set up a repro on a feature branch for you

**Comment by nelsonpecora** [comment]
If these characters are breaking templates and data and other non-kiln stuff, they should be handled elsewhere (NOT by doing logic on the preloaded data that has already been saved). Stripping them from the `text` input will be added in Kiln 5.1.0
