### ISSUE TITLE
idea: validation errors should be indicated for individual items of a complex list

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#931]
## Idea
right now, if there is a validation error, the messaging only says that thole list is invalid. Validation doesn't hook into individual fields

**Comment by nelsonpecora** [comment]
This might be a bit more complicated. It would have to open the form that includes the list, but I'm not sure how we'd specify _which_ item in the list was erroring out.

**Comment by amycheng** [comment]
if [this](https://github.com/clay/clay-kiln/issues/930) is implemented, couldn't the error say "item 5 of complex list has an error"?

**Comment by pfeytser** [comment]
Idea: Refactor validation helpers to be more opinionated and work better with complex lists.

**Comment by nelsonpecora** [comment]
merging this into #1015
