### ISSUE TITLE
bug(?): performance of the complex-list behavior degrades as more and more items are added

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#932]
for example, it's hard to open and scroll the modal. There is no feedback about when the modal has opened or not

**Comment by nelsonpecora** [comment]
How many items does it take to trigger the degradation?

**Comment by fraddski** [comment]
We saw delays of up to 10 seconds to open the modal with approx 480 items (each of which had 8 fields).

**Comment by pfeytser** [comment]
@fraddski What is the minimum number of items where you get perceived slowness?

**Comment by nelsonpecora** [comment]
@pfeytser @fraddski do either of you have example links I can use to test this?

**Comment by nelsonpecora** [comment]
I tried using a virtual scroller, but it doesn't really work with the way our forms calculate their heights (complex-list items not only have variable heights, but their heights change when they're selected)

**Comment by nelsonpecora** [comment]
Cannot figure out a solution to this right now, but it doesn't seem like an urgent issue. We'll keep investigating.

**Comment by fraddski** [comment]
@nelsonpecora this url has the biggest complex list I've seen used: http://www.thecut.com/article/map-sex-and-love-on-the-streets-of-nyc.html

**Comment by nelsonpecora** [comment]
Yikes, that takes 43 seconds to open locally (481 items)
