### ISSUE TITLE
idea (but possibly a bug???): validate timestamps used for scheduled publishing so that users don't accidentally publish pages

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#934]
if the user:
- sets a date from the past, page will immediately publish
- sets the time but not AM or PM, page will immediately publish
- sets the day for the future, but don't set the time, page will immediately publish
- sets the day for the future, set the time, but doesn't set AM or PM, page will immediately publish

## Proposed Solution/Implementation
add logic to the [page-actions pane](https://github.com/clay/clay-kiln/blob/master/panes/publish-pane/page-actions.vue#L141) to checks for:
- if the date is set to the past
- has a time set (I think `date-fns` assumes 12am if there is no time set)

**Comment by amycheng** [comment]
possibly resolved in [kiln 5](https://github.com/clay/clay-kiln/milestone/8) ?

**Comment by nelsonpecora** [comment]
Yep! Let me make sure we catch all of these use cases

**Comment by nelsonpecora** [comment]
Ok, so I'm changing a few things to address this:

* the datepicker's minimum date is set to today, so users won't be able to select a date in the past
* if either a date or time is set (but not both) the button will change to "Schedule" but it will be disabled (it'll enable if both are set)
* "Publish" has been changed to "Publish Now", to further reinforce what will happen when the button is clicked ("Republish" has been changed to "Republish Now")
* on chrome, setting the time without selecting AM/PM will not set the value for that field, so the "Schedule" button will still be disabled
* on firefox, NLP will parse the time, so a value like "5" will be assumed to be 5 am

**Comment by nelsonpecora** [comment]
Two caveats:

* on chrome and firefox. timepicker may be cleared by pressing <kbd>delete</kbd> or (on chrome only) clicking the `X` icon
* datepicker cannot be cleared without refreshing the page

For the second one, I just added a clear icon that'll display when the schedule form has data in it.

![screen shot 2017-10-30 at 2 25 26 pm](https://user-images.githubusercontent.com/447522/32188444-387178e0-bd7e-11e7-9c49-84b6108b6490.png)
