### ISSUE TITLE
Date picker out of view

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#935]
In the custom publish date overlay, when a user clicks the date field, the date picker sometimes appears partially out of view. 

See gif. 

![giphy](https://user-images.githubusercontent.com/447522/32188787-2a73dfde-bd7f-11e7-8098-639b3aa7a2b2.gif)

**Comment by nelsonpecora** [comment]
Hmm, the positioning logic for the datepicker is baked into KeenUI, but I suppose we could switch it to use `modal` rather than the default `popover`

![screen shot 2017-10-30 at 2 33 44 pm](https://user-images.githubusercontent.com/447522/32188891-6f6a6df6-bd7f-11e7-8e73-47c834fd1bb2.png)

**Comment by medihaaziz** [comment]
@pfeytser I also see that circ headline form is not centered. Should I create another ticket for that?

**Comment by pfeytser** [comment]
@medihaaziz It's okay if it's not centered, the issue is if it appears out partially outside of the screen.

**Comment by pfeytser** [comment]
@nelsonpecora Ah okay (re making it a modal not popover). I wish there were a general rule that modals or popovers can touch any edge or go beyond it.
