### ISSUE TITLE
Validation - showing up in incorrect circumstances

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#937]
1. There is no validation error when there is an empty Instagram component. 
2. It shows there is an error for the Ooyala component saying that you must enter the video ID, even when I select "Most Popular Video" as the option. 

See here: http://material-design.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cj98sv07d00000lpsfhqqw3op.html?edit=true#

**Comment by nelsonpecora** [comment]
1. Instagram URLs aren't required ([see schema](https://github.com/nymag/sites/blob/master/components/clay-instagram/schema.yml#L12))
2. looks like there's a bug with `conditional-required`

**Comment by nelsonpecora** [comment]
fixed in kiln 5.0
