### ISSUE TITLE
Tags in affiliate links overlay go off screen

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#939]
When there are more than 4 tags in the affiliate links pane, they go off screen. 

See screenshot. 

![screen shot 2017-10-30 at 1 57 25 pm](https://user-images.githubusercontent.com/10674066/32187145-74ada972-bd7a-11e7-870c-3e2467ceb472.png)

**Comment by nelsonpecora** [comment]
fixed in kiln 5.0
