### ISSUE TITLE
Deep link the Clay menu

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#945]

**Comment by pfeytser** [comment]
@nelsonpecora 
In testing, this link doesn't open Clay menu: http://kiln-510.nymag.sites.aws.nymetro.com/daily/intelligencer/#kiln~all-pages~di~all

**Comment by pfeytser** [comment]
QA Acceptance Criteria

- After I click the Clay menu and navigate to All Pages, I can grab the the URL and open it in a new window. Doing that will automatically open the Clay menu to the All Pages tab.

**Comment by nelsonpecora** [comment]
@pfeytser that link (from github) is being encoded

![image](https://user-images.githubusercontent.com/447522/33096669-dd06436e-ced5-11e7-9467-ca375a181219.png)

**Comment by medihaaziz** [comment]
@pfeytser Passes QA Test link: 
http://kiln-510.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cjaa2wgs4000n0lpapc1mnbey.html?edit=true#kiln~all-pages~bestofny,betamale,di,grubstreet,nymag,nyxny,strategist~all
