### ISSUE TITLE
Bug: New Material Design: Circ Headline form magic button

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#946]
## Bug

1) Go to the feature branch
2) Create an article
3) click article circulation 
4) click twitter/short headline 
5) click the magic button the field never gets populated and the spinner keeps on spinning
![newkiln](https://user-images.githubusercontent.com/4931851/32246101-47c8fddc-be54-11e7-9abf-3a95f8e69d80.png)

**Comment by nelsonpecora** [comment]
I can't reproduce this on my machine.
