### ISSUE TITLE
Bug: New Material Design: Duplicate entries for published articles in MyPages and all pages pane

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#952]
![filterpublish](https://user-images.githubusercontent.com/4931851/32296226-0565d536-bf22-11e7-8d65-52f47e1fad09.png)
## Bug
1) Go to material design branch 
2) create and publish an article 
3) Click on the hamburger icon to the left (clay article menu) 
4) select the published radio button 
5) select all pages and click published radio button, notice there are two entries for that article

![allpages](https://user-images.githubusercontent.com/4931851/32296408-92df933e-bf22-11e7-9679-79d1f88a7741.png)

**Comment by nelsonpecora** [comment]
fixed in kiln 5.0 beta 7
