### ISSUE TITLE
Bug: New Material Design: Adding User Issues

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#953]
## Bug
1) Go to the feature branch 
2) Create an article 
3) Add a user to the article
4) Note the message for adding the user says added *Undefined to this page* 
5) Note it is not adding *user/s* to the contributors pane.
![usernamemissing](https://user-images.githubusercontent.com/4931851/32296730-5e661da2-bf23-11e7-8e86-b1e3c8bfed05.png)

**Comment by nelsonpecora** [comment]
fixed in kiln 5.0 beta 7
