### ISSUE TITLE
Bug: New Material Design: Ooyala player conditional formatting

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#954]
![featureooyala](https://user-images.githubusercontent.com/4931851/32298289-497afb88-bf28-11e7-8b6b-a131de6c1e2a.png)

## Bug
1) Go to the feature branch, create one of the three sponsored articles on the site 
2) Add ooyala player
3) Click publish note there is no warning for empty ooyala id 

![sponsoredooyala](https://user-images.githubusercontent.com/4931851/32298296-528c9542-bf28-11e7-9757-dcc133b38fca.png)

**Comment by medihaaziz** [comment]
![featureooyala](https://user-images.githubusercontent.com/4931851/32298289-497afb88-bf28-11e7-8b6b-a131de6c1e2a.png)


![sponsoredooyala](https://user-images.githubusercontent.com/4931851/32298296-528c9542-bf28-11e7-9757-dcc133b38fca.png)

**Comment by nelsonpecora** [comment]
This is expected. Only non-permanent placeholders get validation / error styling
