### ISSUE TITLE
Bug: New Material Design: Health Check for Required Fields

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#955]
## Bug
1) go to the feature branch
2) Create a new article 
3) Without editing anything click publish
4) Note it throws a publishing error without indicating to the user that they are missing required fields.

**Comment by nelsonpecora** [comment]
Hmm, looks like there's something up with the validation logic.

**Comment by nelsonpecora** [comment]
Ok, it was just the `required` validator. Fixed in commit 525f52a
