### ISSUE TITLE
Bug: New Material Design: Error Publishing Page

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#956]
## Bug
1) Go to the feature branch
2) create a new article 
3) click publish
4) enter all the required fields 
5) click publish 
6) note it still throws an error saying error publishing the page, until the user hard refreshes. 

please see attached screenshot of what happens in the console. 
![image](https://user-images.githubusercontent.com/4931851/32330391-63f9c78a-bfb6-11e7-89ea-1f9964bdb3f6.png)

**Comment by nelsonpecora** [comment]
I can't repro this now that https://github.com/clay/clay-kiln/issues/955 is fixed
