### ISSUE TITLE
Update Page and Layout Data

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#958]
Now that all layouts re-render client-side, we need to update the saving/rendering loop to re-enable support for changing component lists in the layout (including changing page data).

## Triggers

* component list dragdrop
* head components drawer dragdrop
* invisible components drawer dragdrop
* component list add / remove
* head components drawer add / remove
* invisible components drawer add / remove

## Saving Data

* saving layout data
* saving page data

## Rendering

* rendering head lists
* rendering body lists (including invisible lists)

**Comment by pfeytser** [comment]
Acceptance criteria: 
- [ ] I can drag and drop components in the layout. 
- [ ] I can add new components to the layout
- [ ] I can delete components from the layout
