### ISSUE TITLE
Can't add users to Clay for Amphora 5

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#960]
When I tried to add a user to the Amphora 5 branch, it threw an error. 

Request is not underscored

`
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /daily/intelligencer/users</pre>
</body>
</html>
`

Screenshot for console: 

![screen shot 2017-11-02 at 4 48 25 pm](https://user-images.githubusercontent.com/10674066/32349521-c2d6baec-bfed-11e7-9139-ef6f094a40ed.png)

**Comment by nelsonpecora** [comment]
dupe https://github.com/clay/clay-kiln/issues/959
