### ISSUE TITLE
Can't add Tweet on this article

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#964]
Also, won't let me delete things on this article. 

http://material-design.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cj9jyep3x00000vqb9acgu4cc.html?edit=true#

![screen shot 2017-11-03 at 9 55 44 am](https://user-images.githubusercontent.com/10674066/32377167-3068665c-c07d-11e7-915e-6b7623f09eeb.png)

After this happens, I go to the Clay menu and page templates won't load

![screen shot 2017-11-03 at 9 56 56 am](https://user-images.githubusercontent.com/10674066/32377244-5eac044c-c07d-11e7-8bfe-49c66af84676.png)
#

Even after refresh, page templates won't load on this article.

**Comment by nelsonpecora** [comment]
pushing a fix for the tweet schema
