### ISSUE TITLE
Bug: New Material Design: Circ Metadata

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#967]
## Bug
1) go to the feature branch
2) create a new article
3) enter all the information 
4) click on article recirculation to select feature types 
5) note you cannot select the feature types
![circmetadatadropdown](https://user-images.githubusercontent.com/4931851/32384361-0effc7ee-c091-11e7-8666-3ac993fed5e2.png)
![circmetadata](https://user-images.githubusercontent.com/4931851/32384364-1059ba64-c091-11e7-908e-f2d450d64eab.png)

**Comment by nelsonpecora** [comment]
Looks like there's a bug with `select`'s data, when we allow `multiple` selection

**Comment by nelsonpecora** [comment]
fixed in commit 2aeccf9
