### ISSUE TITLE
Bug: New Material Design: Single Related Story

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#968]
## Bug
1) go to feature branch create a new article
2) click to add component
3) search for single related story
4) try to add it,.It throws an error in console and in kiln see attached screenshots, 
![image](https://user-images.githubusercontent.com/4931851/32384484-6da47a92-c091-11e7-9e95-bb0b595a7c4c.png)

![singlerelatedstory](https://user-images.githubusercontent.com/4931851/32384524-99d2fb0c-c091-11e7-87dc-3adbe78d365e.png)

**Comment by nelsonpecora** [comment]
fixed in sites
