### ISSUE TITLE
Bug: New Material Design: Max instances

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#973]
## Bug
1) go to feature branch, create a new article, or open this [one](http://material-design.nymag.sites.aws.nymetro.com/strategist/2017/11/testing-out-the-products-on-here.html?edit=true#) 
2) add multiple single related story components
3) delete all of them or keep one of them try to publish. 
Note the max instances warning will appear blocking publishing or republishing of the article

![maxinstance](https://user-images.githubusercontent.com/4931851/32447889-5ec5f004-c2db-11e7-8e37-329ec4cfc80a.png)

**Comment by nelsonpecora** [comment]
Hmm, I think this validator might not be working properly. I'll investigate.

**Comment by nelsonpecora** [comment]
fixed in sites (commit 15a7d90d2)
