### ISSUE TITLE
Bug: New Material Design: Paragraph settings

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#974]
## Bug
1) go to the feature branch (I saw this issue on Strat). Create a new article. 
2) Paste some paragraphs
3) Try to click into the paragraph and try to click any available setting or addition of a component. 
Note the pane for the settings disappears on hover to the left. 

See this video:

https://drive.google.com/file/d/0B-A8W9KJ5JJlUWlFMnZUaXNWenM/view

**Comment by nelsonpecora** [comment]
This is expected behavior. In kiln 5.x, components will be selected / unselected when you hover over them
