### ISSUE TITLE
Bug: New Material Design: Paragraph should be required

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#979]
## Bug
1) go to feature branch create an article I tested on full bleed lede
2) instead of paragraph add some other component, fill in all the required fields. 

Note it will allow you to publish without a paragraph 

check this link: 
http://material-design.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cj9pvaz00008l1znz9888uto4.html

**Comment by nelsonpecora** [comment]
I don't see any empty paragraphs on that page.
