### ISSUE TITLE
Video page design has not been updated

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#980]
What the new design looks like: 
http://nymag.com/daily/intelligencer/2017/11/virginias-first-transgender-candidate-for-state-legislature.html

What is currently on the `material-design` branch:
http://material-design.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cj9pygtpr00au1znzvseu11yy.html?edit=true

**Comment by nelsonpecora** [comment]
rebuilding sites
