### ISSUE TITLE
Bug: Contributors pane doesn't update in the same session

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#985]
## Bug
1) go to any site, create an article. 
2) add a contributor to that article note it doesn't show them right away you need to refresh the page.

**Comment by medihaaziz** [comment]
@nelsonpecora I am not seeing this work on prod

**Comment by nelsonpecora** [comment]
This is working for me on prod

![](http://up.keats.me/1l0B3o203025/Screen%20Recording%202017-11-09%20at%2011.27%20AM.gif)
