### ISSUE TITLE
Bug: After adding a contributor 

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#986]
## Bug
1) Go to any site create a new page
2) add a contributor
3) refresh the page, not there is a message saying that the last contributor you added edited the page in less than 5 mins ago. That might not be true. Was not true in my scenario.

**Comment by nelsonpecora** [comment]
I'm not quite sure I understand. What's the expected functionality, and what's actually happening?

**Comment by medihaaziz** [comment]
@nelsonpecora will come over to show you
