### ISSUE TITLE
Bug? Clicking outside of simple-list items will remove some

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#991]
![kiln-bug](https://user-images.githubusercontent.com/1660273/32631430-3899c780-c56e-11e7-99b7-643ec2b024f0.gif)

**Comment by nelsonpecora** [comment]
Huh, that's super weird. Are they being hidden, or actually removed from the data?

**Comment by cperryk** [comment]
@nelsonpecora They're removed.

**Comment by pfeytser** [comment]
QA Acceptance Criteria

- Clicking outside of tags in the tags overlay does nothing (see bug above)

**Comment by medihaaziz** [comment]
@pfeytser Passes QA http://kiln-510.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cjaa2wgs4000n0lpapc1mnbey.html?edit=true#tags~cjaa2wgsp000v0lpaaccbwycz~items
