### ISSUE TITLE
Autocomplete appears out of view

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#992]
![screen shot 2017-11-10 at 10 31 33 am](https://user-images.githubusercontent.com/10674066/32665549-a736fffc-c602-11e7-94d8-8c8c961a2917.png)

**Comment by nelsonpecora** [comment]
I noticed this before, but I'm still trying to figure out the best way to fix it. What's happening is that the form is scrollable, so the autocomplete increases the form height. and makes the scroll bar appear (if it wasn't there already). There are a few options that might work to address this:

1. trigger a height change in the wrapper modal. this is what complex-list does when you add items, and it'll make the form taller. PROS: no scrolling. CONS: the form will resize, which might be a bit visually loud.
2. somehow figure out how to make the autocomplete (and only the autocomplete) overflow the form. Short of using a bunch of js to attach it to the `<body>` and position it below the field (which will be weird if users scroll the form) I'm not sure how to accomplish this.

What are your thoughts?

**Comment by pfeytser** [comment]
The main problem with option 1 is that the overlay shrinks after you delete a source link. If it stayed larger after expanding, that would be okay. 

The only other thing I could think of is just making the overlays for tags and byline taller, align the form field to the top so there is some room below, but that's not great. 

I think your option 2 is the best one from a UX perspective.

**Comment by pfeytser** [comment]
Be it agreed that overlaying the autocomplete is the ideal solution.

**Comment by nelsonpecora** [comment]
Option 2 requires a whole lot more work than option 1, and has downsides when scrolling. I figured out a way to do option 1 in a way that isn't too onerous

**Comment by pfeytser** [comment]
@nelsonpecora Where can I test the solution you went with?

**Comment by nelsonpecora** [comment]
I'll be on a feature branch with v5.1.0 when that release is ready

**Comment by medihaaziz** [comment]
@pfeytser passes QA http://kiln-510.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cjaa4rgbc00000vmchfojj3wj.html?edit=true#tags~cjaa4rgcl00080vmcifjx9yue~items
