### ISSUE TITLE
Bug? There's no way to clear a datepicker

### ISSUE THREAD

**Issue by cperryk** [clay/clay-kiln#993]
We had an editor try to clear an optional `datepicker` field, but the UI provides no way of clearing its value once set, only of selecting a different one.

**Comment by nelsonpecora** [comment]
This comes from a limitation of [KeenUI's Datepicker](https://josephuspaye.github.io/Keen-UI/#/ui-datepicker). We got around it in the publish pane by having an icon button that clears both the date and time, and maybe we could do a similar thing for this input?

If we sacrificed the ability to have an `attachedButton` on `datepicker` inputs, we could use that space for a "clear" button. Are the tradeoffs worth it? (are there any scenarios where you could see someone wanting a lock or magic-button on datepickers? I can think of a few, but none of them are mission-critical)

**Comment by cperryk** [comment]
@nelsonpecora I don't know of any cases currently where we need both a datepicker and a magic button or lock. If those cases were to arise, might it be possible to show both buttons side-by-side?

**Comment by nelsonpecora** [comment]
I originally didn't want to allow multiple attached buttons, but there's no technical issue preventing them. (They would just be a bit cluttered / visually noisy). I could see them being useful for stuff like image url fields (`feedImgUrl` might want to either pull the first mediaplay-image url (via magic button) _or_ open a mediaplay picker)

**Comment by nelsonpecora** [comment]
Per the KeenUI discussion, it looks like this will be handled natively. Going to hold off on implementing something custom until that's addressed.
