### ISSUE TITLE
Make the entire SEO description content visible

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#994]
From the #help channel

<img width="975" alt="screen shot 2017-11-10 at 5 45 33 pm" src="https://user-images.githubusercontent.com/10674066/32681765-1f833930-c63f-11e7-855a-25d00b475ffb.png">

**Comment by nelsonpecora** [comment]
Hmm, this is an interesting request. Basically, our `wysiwyg` expands down when the text overflows the input, whereas `text` scrolls to the right (which is the affordance that native text `<input>` tags have). Multi-line text inputs use `<textarea>`, which also expands, but it also allows <kbd>enter</kbd> and empty lines. It doesn't seem like there's a way to make the regular `text` inputs expand in the way this user wants.

**Comment by nelsonpecora** [comment]
After doing some investigation, the current affordances are ingrained in both KeenUI and native browser inputs. I'm going to mark this as closed, with the caveat that component authors can use `wysiwyg` or `multi-line` text inputs to product the desired effect.

**Comment by pfeytser** [comment]
@nelsonpecora So would that be a simple schema change to `multi-line`? I want to create a ticket elsewhere for this feature request.

**Comment by nelsonpecora** [comment]
Yep, if you want to allow people to add line breaks (You might not want to allow that, but it's a nymag product decision, rather than platform stuff). Docs for `multi-line` text inputs are [here](https://claycms.gitbooks.io/kiln/inputs.html#text)
