### ISSUE TITLE
Bug: "Edit page" doesn't work after following in-page link

### ISSUE THREAD

**Issue by fraddski** [clay/clay-kiln#995]
The "Edit page" button doesn't strip URL fragments, so using it after following an in-page link doesn't have any effect.

**Comment by nelsonpecora** [comment]
Ah! We should fix this.

**Comment by pfeytser** [comment]
QA Acceptance Criteria:

- On this page, after I click the "Jump to List of Competitive Seats" button, I can click the "Edit page" button on the top left and it will take me to edit mode. 
http://nymag.com/daily/intelligencer/article/2018-midterm-election-tracker-house.html

**Comment by medihaaziz** [comment]
@pfeytser not sure how to test this on the feature branch

**Comment by nelsonpecora** [comment]
If you go to a page (in view mode), then add some random `#hash-link`, then go into edit mode, it should strip out whatever `#hash-link` you added.
