### ISSUE TITLE
Bug: Unable to add new users through `Invite To Clay` modal

### ISSUE THREAD

**Issue by byronhulcher** [clay/clay-kiln#996]
## Bug
When I try to add a new user to a Clay site using the `Invite To Clay` modal in updated Kiln, the user is not added even though I get a toast stating the user was added.
![image](https://user-images.githubusercontent.com/2479295/32743300-00922b7a-c87a-11e7-98cc-56653b84b181.png)

## Repro
1. Go into edit mode of a clay page as an Admin (I used http://www.thecut.com/?edit=true)
2. Open the Clay Menu
3. Click `Users`
4. Click `Invite To Clay`
5. Enter a username (I entered `jason.tseng@nymag.com`)
6. Click `Invite To Clay`
7. Observe toast confirming invitation (I saw `Added jason.tseng@nymag.com to Clay`)

Expected:
8. I can search for the user in the `Users` pane and the added user appears
9. The user is able to login

Actual
8. The user does not appear in the `Users` pane
9. The user is unable to login

## Notes
It looks like this might be caused by a redirect issue? 

In Chrome DevTools, I'm seeing a POST to `http://www.thecut.com/users` which receives a 301 response with `Location: http://www.thecut.com/users/` as one of its headers. 
<img width="589" alt="screen shot 2017-11-13 at 2 00 14 pm" src="https://user-images.githubusercontent.com/2479295/32743656-092392b4-c87b-11e7-8246-5fb8d7d3328f.png">

This is followed by a **GET** to `http://www.thecut.com/users/` but without the form data.
<img width="589" alt="screen shot 2017-11-13 at 2 00 21 pm" src="https://user-images.githubusercontent.com/2479295/32743668-0fed1b2e-c87b-11e7-972a-1d7edb438c58.png">

**Comment by pfeytser** [comment]
@byronhulcher Is this on the Cut?

**Comment by byronhulcher** [comment]
@pfeytser yep

**Comment by pfeytser** [comment]
@byronhulcher It's not a Kiln issue, working with ops to resolve (when you try to do the POST, it's adding a trailing slash for some reason)

**Comment by pfeytser** [comment]
@byronhulcher Actually that bug I was just referring to has been fixed... @nelsonpecora Maybe it is a Kiln problem?

**Comment by nelsonpecora** [comment]
Are you sure the user isn't being added? Are you searching for them with their email? (If they haven't logged in yet, searching for their name won't yield any results)

Also, you can directly see if they've been added by doing a GET request to /users/<email @ google, base64 encoded> to see if that information exists on the server

**Comment by nelsonpecora** [comment]
Ah right. I'm not sure why a POST to /users is returning a 301, but that's the culprit (all of our POSTS are to routes _without_ a trailing slash). @larrychevres might have more info?

**Comment by byronhulcher** [comment]
Ah okay, so `/users` is the canonical url? I guess it is ops

**Comment by nelsonpecora** [comment]
Yep!
