### ISSUE TITLE
Expanding click area of wysiwyg formatting tools 

### ISSUE THREAD

**Issue by terrineal** [clay/clay-kiln#997]
## Idea/Suggestion

Was brought up on the #help channel that 

> there's a bug that prevents me from adding or removing itals (or other styling) within heds in the Article Circulation section.

After a little investigation and asking around, came to the conclusion that it's not actually a "bug" but that the hit/click area for these buttons may not be large enough. Just wanted to suggest possibly making the hit area for these buttons a little bigger.

**Comment by pfeytser** [comment]
Clay Kiln will expand click area to meet Material Design requirements.

**Comment by nelsonpecora** [comment]
![screen shot 2017-11-20 at 2 00 53 pm](https://user-images.githubusercontent.com/447522/33036039-45326f16-cdfb-11e7-8eef-c3429cc4d97f.png)

**Comment by pfeytser** [comment]
QA Acceptance Criteria

- The WYSIWYG formatting toolbar is large as the icons in the top Clay toolbar.

**Comment by nelsonpecora** [comment]
They're not as large as the toolbar icons, but they'll be about the same size as the selector icons.

**Comment by medihaaziz** [comment]
@nelsonpecora The strike through format is not working should that be related to this or something else? http://kiln-510.nymag.sites.aws.nymetro.com/daily/intelligencer/pages/cjaa2wgs4000n0lpapc1mnbey.html?edit=true#article~cjaa2wgsr00190lpaga1qq9dt~overrideHeadline

**Comment by nelsonpecora** [comment]
I believe that's something else, since it's working for me locally.
